"""Editable content for the Starplast overview and practical usage deck.

Numbers describe the 0.43 release dataset. Screenshots come from the real app;
the comparison example is labelled illustrative, and benchmarks retain their
evaluation context. Keep the deck below 50 slides and favour one idea per page.
"""
BASE = 'https://einarolafsson.github.io/starplast/'


def slide(title, section, layout='cards', **content):
    """Declare one slide and its supporting user documentation."""
    return dict(title=title, section=section, layout=layout,
                source=BASE + content.pop('source', 'guide.html'), **content)


SLIDES = [
    slide('Starplast', 'GENE EVIDENCE, IN CONTEXT', 'cover',
          lead='Explore what is known.\nEvaluate what a model predicts.',
          note='A practical guide to the 0.43 release', source='index.html'),
    slide('Start with a gene. Keep the evidence.', 'INTRODUCTION', 'flow',
          lead='Bring scattered measurements together without losing what they mean.',
          cards=[('Collect', 'Published measurements, annotations and protein features.'),
                 ('Connect', 'Match gene identities and retain the source of each value.'),
                 ('Explore', 'Read evidence, compare relationships and inspect gaps.'),
                 ('Evaluate', 'Test predictions on held-out genes before interpreting them.')],
          note='A model suggests a hypothesis. Its evidence and validation determine how useful it is.'),
    slide('Two organisms. Separate maps.', 'INTRODUCTION', 'stats',
          lead='Offline gene tables and networks are included in the installation.',
          cards=[('8,140', 'Toxoplasma gondii genes'), ('5,720', 'Plasmodium falciparum genes'),
                 ('130', 'Registered datasets and computed layers')],
          note='Coverage differs by assay and organism. These counts do not imply complete evidence for every gene.',
          source='datasets.html'),
    slide('Choose the task you came to do.', 'INTRODUCTION',
          cards=[('Explore a gene', 'Find an accession, symbol or product. Read measurements and their sources.'),
                 ('Predict a trait', 'Choose an observed outcome. Evaluate a model, then inspect unlabelled-gene hypotheses.'),
                 ('Compare a screen', 'Join a gene-level results table to the existing evidence. Keep unresolved IDs visible.')],
          note='Open these guided workflows from the Tools menu.', source='workflows.html'),
    slide('The map is one view of the evidence.', 'INTRODUCTION', 'image', image='map-dark.png',
          lead='One point represents one gene.',
          cards=[('Position', 'Similarity under the chosen feature recipe.'),
                 ('Colour', 'An annotation or measurement you select.'),
                 ('Lines', 'One explicitly selected relationship type.')],
          note='Proximity alone does not establish function or a physical interaction.'),
    slide('Install and open Starplast.', 'GET STARTED', 'code',
          code='pip install starplast\nstarplast',
          cards=[('Python 3.10+', 'Use a dedicated environment when possible.'),
                 ('Desktop display', 'The viewer needs a display and working OpenGL.'),
                 ('CPU included', 'CUDA is optional; browsing does not require a GPU.')],
          note='Linux, macOS and Windows. Built tables are available offline.', source='releases.html'),
    slide('Your first five minutes.', 'GET STARTED', 'flow',
          cards=[('1  Choose', 'File > Species: select the organism.'),
                 ('2  Search', 'Tools > Explore a gene: enter an accession or product.'),
                 ('3  Inspect', 'Read the evidence and open its source links.'),
                 ('4  Compare', 'Change a colour or edge layer; keep the question specific.')],
          note='Start with one familiar gene so you can check that the interpretation makes sense.'),
    slide('Find your way around the workspace.', 'GET STARTED', 'fullimage', image='workspace.png',
          lead='Map controls on the left. The gene map in the centre. Evidence on the right.',
          note='Tools opens guided workflows and analysis docks. View controls appearance and interaction.'),
    slide('Move the map. Keep your bearings.', 'EXPLORE',
          cards=[('Rotate and zoom', 'Left-drag in Navigate mode to rotate. Scroll to move closer or farther away.'),
                 ('Select a gene', 'Click a point to show its evidence. Search can take you directly to a gene.'),
                 ('Focus a category', 'Filter checked categories. Double-click a category to centre its genes.')],
          note='Right-click the map for display options, export and reset.'),
    slide('Search by identity or description.', 'EXPLORE', 'image', image='explore.png',
          lead='Tools > Explore a gene',
          cards=[('Enter a query', 'Use a gene accession, symbol or product text.'),
                 ('Check the match', 'Double-click a result to select the same gene on the map.'),
                 ('Read the table', 'Inspect available values, missingness and source evidence.')],
          note='Shown here: an existing alpha-tubulin record, not a model-generated annotation.', source='workflows.html'),
    slide('Read the source, not just the value.', 'EVIDENCE',
          cards=[('What was measured?', 'Distinguish expression, localization, abundance, sequence and interaction evidence.'),
                 ('In which context?', 'Check the organism, stage, condition and assay before comparing measurements.'),
                 ('How was it obtained?', 'Separate measured evidence, computed features, transferred annotations and predictions.')],
          note='Legacy gene summaries cannot reconstruct replicate-level uncertainty that was never retained.',
          source='workflows.html'),
    slide('The full data catalogue stays one click away.', 'EVIDENCE', 'table',
          columns=['Evidence family', 'Examples', 'Read it as'],
          rows=[['Expression', 'Stage profiles and summaries', 'Condition-dependent measurements'],
                ['Localization', 'Compartment annotations', 'Evidence with assay-specific coverage'],
                ['Protein features', 'Sequence, domains, AF3 summaries', 'Measured or computed descriptors'],
                ['Relationships', 'Coexpression and physical assays', 'Distinct types of connections'],
                ['Literature', 'Mentions and reviewed assertions', 'Traceable source context']],
          note='Each catalogue record links to its publication, source data or computed inputs.', source='datasets.html'),
    slide('Unknown is different from zero.', 'EVIDENCE', 'stats',
          cards=[('0', 'A measured value that really is zero'),
                 ('Unknown', 'No usable value is available'),
                 ('No call', 'The model lacks enough support')],
          note='A missing annotation is not a negative example. Grey marks unknown evidence.', source='workflows.html'),
    slide('Different lines answer different questions.', 'RELATIONSHIPS', 'network',
          cards=[('Similarity', 'Shared domains, orthogroups, expression or structure.'),
                 ('Physical evidence', 'Crosslink MS and pulldown assays have their own interpretation.'),
                 ('Literature context', 'Co-mention means appearing together in text; it is not proof of binding.')],
          note='The Edges controls keep these layers separate.'),
    slide('Inspect one connection layer at a time.', 'RELATIONSHIPS', 'flow',
          cards=[('Select', 'Click a gene you want to inspect.'),
                 ('Choose', 'Turn on a relevant layer in Edges.'),
                 ('Read', 'Check neighbouring genes and the evidence behind the relation.'),
                 ('Compare', 'Switch the layer and see which relationships persist.')],
          note='Draw all active edges is available, but dense networks are often easier to understand locally.'),
    slide('Select a group without changing the data.', 'EXPLORE', 'selection',
          cards=[('Lasso: screen space', 'Draw an outline around visible positions. Points behind one another can be included.'),
                 ('Brush: 3D space', 'Select a spatial neighbourhood around the gene you press.')],
          note='Choose View > Left mouse button > Select. Check the selected gene list before exporting.'),
    slide('Explore clusters and compare analyses.', 'ADVANCED ANALYSIS',
          cards=[('Clusters', 'Group similar coordinates with clustering methods. Noise label -1 means unassigned, not a biological class.'),
                 ('Search and validation', 'Compare recipes with explicit targets and budgets. Confirm a search winner with independent evidence.'),
                 ('Saved results', 'Name embeddings and retain their recipes. Right-click result tables to export them; save selected gene lists.')],
          note='Cluster labels describe the chosen inputs. They do not establish a shared biological function.'),
    slide('Change a map deliberately.', 'ADVANCED MAPS', 'flow',
          cards=[('Features', 'Choose relevant measurement blocks.'),
                 ('Missingness', 'Decide how absent inputs are handled.'),
                 ('Scaling', 'Keep feature magnitudes and blocks comparable.'),
                 ('Embedding', 'Choose a method, dimensions and a seed.')],
          note='Smaller UMAP neighbourhoods favour local structure. Lower minimum distance packs points more tightly.'),
    slide('Explore in 3D. Evaluate separately.', 'PREDICTION', 'split',
          cards=[('The displayed map', 'An exploratory view of selected inputs. Numeric localization confidence can be among them.'),
                 ('A held-out prediction', 'A separate fitted model with target exclusions, training-only transforms and untouched evaluation groups.')],
          note='The guided predictor does not classify the opening map.', source='workflows.html'),
    slide('Set up a prediction in one place.', 'PREDICTION', 'image', image='predict.png',
          lead='Tools > Predict a trait',
          cards=[('Outcome and type', 'Choose the observed target and classification or regression.'),
                 ('Method and groups', 'Start with a baseline. Keep related genes together with orthogroup.'),
                 ('Run and inspect', 'Evaluate and predict. Read held-out metrics before the candidate table.')],
          note='The Jobs panel runs the work. Stop requests cancellation between model fits.', source='workflows.html'),
    slide('Keep evaluation genes out of fitting.', 'PREDICTION', 'folds',
          cards=[('Fit', 'Learn features and model parameters.'),
                 ('Calibrate', 'Adjust probabilities or residual intervals on separate groups.'),
                 ('Evaluate', 'Score predictions on groups withheld from both steps.')],
          note='Outer folds rotate the evaluation groups. Grouped validation is harder and more informative than mixing relatives.',
          source='benchmark-0.43.html'),
    slide('Compare simple methods first.', 'PREDICTION', 'table',
          columns=['Method', 'Useful starting question', 'Keep in mind'],
          rows=[['Prior / linear', 'Is there signal beyond a simple baseline?', 'Always retain a baseline'],
                ['Boosted trees', 'Do nonlinear feature combinations help?', 'Use the same evaluation groups'],
                ['Feature / PCA neighbours', 'Do similar measured genes agree?', 'Distance depends on preprocessing'],
                ['UMAP / masked factors', 'Does a reduced representation help?', 'A compact map can lose signal'],
                ['Weighted networks', 'Which fixed graph layers support labels?', 'Transductive; disconnected genes abstain']],
          note='No method is automatically best because it is more complex.', source='workflows.html'),
    slide('Read performance and coverage together.', 'PREDICTION',
          cards=[('Accuracy', 'The fraction of evaluation genes called correctly. Unsupported calls count as misses.'),
                 ('Macro F1', 'Balances precision and recall across classes, so common labels do not dominate the score.'),
                 ('Coverage', 'The fraction with a supported call. Selective accuracy describes only that supported subset.')],
          note='Also inspect per-class precision, recall, average precision and calibration.', source='workflows.html'),
    slide('What worked in the localization benchmark?', 'RESULTS', 'metrics', metric='localization',
          lead='3,827 measured genes · 26 classes · three orthogroup-held-out folds',
          cards=[('0.434 macro F1', 'Boosted trees with published, AF3 and ESM inputs.'),
                 ('56.2% accuracy', 'Better than the compared UMAP-neighbour models.'),
                 ('Important limit', 'Several rare classes still have zero top-class recall.')],
          note='Development cross-validation, not prospective validation of new annotations.', source='benchmark-0.43.html'),
    slide('A confident score can still be wrong.', 'RESULTS', 'metrics', metric='calibration',
          lead='Combined boosted model: observed accuracy in held-out confidence bins',
          cards=[('Check calibration', 'Temperature scaling uses separate groups when enough labels exist.'),
                 ('Read the status', 'The app explicitly marks runs that could not be calibrated.'),
                 ('Use abstention', 'A probability cutoff can withhold uncertain calls; it is not a guarantee.')],
          note='The 0.8-0.9 bin averaged 0.850 confidence but 0.783 accuracy across 465 genes.', source='benchmark-0.43.html'),
    slide('Add sequence evidence with one checkbox.', 'PROTEIN EVIDENCE', 'coverage', metric='sequence',
          cards=[('8,064 proteins', 'Bundled frozen ESM-2 representations.'),
                 ('320 features', 'A numerical view of protein sequence, separate from experimental measurements.'),
                 ('No download to use', 'Enable Include frozen protein sequence features in the guided predictor.')],
          note='Regenerating representations needs the optional sequence extra. Benchmark their value rather than assuming it.',
          source='protein-sequences.html'),
    slide('Your AF3 collection becomes traceable evidence.', 'PROTEIN EVIDENCE', 'coverage', metric='structure',
          cards=[('1,210 matched genes', 'Exact sequence or uniquely placed fragment matches in the available local collection.'),
                 ('Nine summary features', 'Confidence, sequence coverage and descriptive geometry.'),
                 ('Coordinates stay local', 'The package includes features and provenance, not the private model files.')],
          note='This is the verified subset in the synced folders, not the total number of proteins ever folded.',
          source='structures.html'),
    slide('Connect local folds to the structure viewer.', 'PROTEIN EVIDENCE', 'code',
          code="pip install 'starplast[structures]'\n\nstarplast-index-structures /path/to/models",
          cards=[('Index once', 'Build the local structure catalogue from your model folders.'),
                 ('Select a gene', 'The structure viewer checks the local index before AlphaFold DB.'),
                 ('Read confidence', 'A predicted fold and its confidence are not experimental validation.')],
          note='Recreate the index if the drive moves. Full models take precedence over fragments.', source='structures.html'),
    slide('Continuous traits stay continuous.', 'RESULTS', 'metrics', metric='abundance',
          lead='Protein abundance: 748 measured genes · grouped held-out evaluation',
          cards=[('Choose regression', 'Use Continuous measurement instead of converting an outcome into classes.'),
                 ('Read error units', 'RMSE here is measured in log2 abundance units; lower is better.'),
                 ('Small added gain', 'The combined-feature improvement interval includes no improvement.')],
          note='Nominal 90% intervals covered 94.9%, but their mean width was 9.94 log2 units.', source='benchmark-0.43.html'),
    slide('Network coverage is not prediction quality.', 'RESULTS', 'split',
          cards=[('87.3% supported', 'Combining domain, expression and structural layers reaches more evaluation genes.'),
                 ('0.195 macro F1', 'The combined fixed network remains well below the compared feature models.')],
          note='The graph includes evaluation nodes: report these results as transductive, not transfer to unseen nodes.',
          source='benchmark-0.43.html'),
    slide('Compare a screen without losing unmatched rows.', 'SCREEN WORKFLOW', 'image', image='compare.png',
          lead='Tools > Compare a screen',
          cards=[('Open a CSV or TSV', 'Use a gene-level table and choose its identifier and value columns.'),
                 ('Inspect the join', 'Mapped and unresolved IDs remain visible. Measured zero stays zero.'),
                 ('Export the comparison', 'Keep the table and source-file hash together.')],
          note='Screenshot values are illustrative. They are not biological screen results.', source='workflows.html'),
    slide('Move from spaCR results to gene evidence.', 'SCREEN WORKFLOW', 'flow',
          cards=[('spaCR', 'Generate gene-level measurement or effect estimates.'),
                 ('CSV / TSV', 'Export identifiers and the measured value you want to compare.'),
                 ('Starplast', 'Open Compare a screen and inspect the identifier mapping.'),
                 ('Evidence', 'Read the existing annotations and source context alongside the result.')],
          note='The spaCR launcher opens Starplast in a separate environment. It does not automatically transfer results.',
          source='workflows.html'),
    slide('Add measurements to a Toxoplasma session.', 'SCREEN WORKFLOW',
          cards=[('File > Import data', 'The advanced importer accepts CSV, TSV, Excel or Parquet for Toxoplasma accessions.'),
                 ('Check the preview', 'Choose a useful column prefix and explicitly handle duplicates and missing values.'),
                 ('Rebuild deliberately', 'Imported values do not change map positions until you include them in a new embedding.')],
          note='Advanced table import is Toxoplasma-only. The guided comparison supports the currently open organism.'),
    slide('Export the evidence behind a result.', 'REPRODUCIBILITY', 'flow',
          cards=[('predictions.csv', 'Separate held-out evaluations from unknown-gene hypotheses.'),
                 ('per_class.csv', 'Inspect performance and support for each class.'),
                 ('run.json', 'Retain settings, input identity, split genes, excluded features and versions.')],
          note='Use Export full run. A ranked list alone cannot reproduce an analysis.', source='workflows.html'),
    slide('Use the same methods from Python.', 'PYTHON API', 'code',
          code="import pandas as pd\nfrom starplast import paths\nfrom starplast.prediction import TaskSpec, run\n\nnodes = pd.read_parquet(\n    paths.cache_file('nodes.parquet'))\nresult = run(nodes, TaskSpec('compartment'))\nresult.save('localization_run')",
          cards=[('Headless analysis', 'Read bundled tables and run methods without opening the desktop.'),
                 ('One contract', 'The API uses the same evaluation and export rules as the guided workflow.')],
          note='The generated module reference documents functions, arguments and return values.', source='API.html'),
    slide('Keep claims traceable and reviewable.', 'EVIDENCE API',
          cards=[('Observation records', 'Store entity, trait, value, units, context, source, uncertainty and missingness.'),
                 ('Literature assertions', 'Retain the source passage and negation. Extracted claims begin pending review.'),
                 ('Explicit limits', 'The API supports review records; the desktop has no bulk literature-curation interface.')],
          note='A reviewed interpretation of a passage is not experimental proof. Conflicting observations remain separate.',
          source='workflows.html'),
    slide('Run work in the background. Keep control.', 'PRACTICAL USE',
          cards=[('Jobs and Stop', 'Watch progress in the Jobs panel. Cancellation happens between model fits.'),
                 ('Optional GPU', 'CPU analysis is the default. NVIDIA CUDA analysis uses the gpu extra on supported Linux systems.'),
                 ('Logs and help', 'Hover over settings. Enable file logging in Preferences when investigating a problem.')],
          note='Offline browsing works immediately. Remote structures, publications and optional chat can require network access.'),
    slide('Choose a readable view.', 'APPEARANCE', 'themes',
          lead='View > Preferences: theme, colours, point rendering, lighting and text size.',
          note='Lighting changes presentation only. Use neutral lighting when comparing measurement colours.'),
    slide('Before interpreting a prediction, check four things.', 'GOOD PRACTICE', 'flow',
          cards=[('Identity', 'Are the gene mapping, organism and assay context correct?'),
                 ('Evidence', 'Which values are measured, computed, missing or transferred?'),
                 ('Validation', 'Were target-related inputs excluded and related genes held together?'),
                 ('Uncertainty', 'Do rare classes, calibration and coverage support the intended interpretation?')],
          note='Model comparisons guide exploration. Independent evidence is needed to establish a new biological claim.',
          source='benchmark-0.43.html'),
    slide('Open a gene. Ask a precise question.', 'START HERE', 'end',
          lead='pip install starplast',
          cards=[('User guide', BASE+'guide.html'), ('Guided workflows', BASE+'workflows.html'),
                 ('Data sources', BASE+'datasets.html'), ('Python API', BASE+'API.html'),
                 ('Benchmarks', BASE+'benchmark-0.43.html'),
                 ('Issues and source', 'https://github.com/EinarOlafsson/starplast')],
          note='Starplast · Einar Olafsson · Open-source software, with original data sources credited.', source='index.html'),
]
