#!/usr/bin/env python3
"""The slot table: one row per question the map can ask, graded against the shipped cache.

A slot is a QUESTION -- "how much is this gene transcribed in an IFN-gamma-stimulated macrophage" --
not a dataset and not a column family. Two consequences, and both are why this file exists rather
than a paragraph of prose:

* **The condition is part of the question.** Transcription in a naive macrophage and transcription
  in an IFN-gamma-stimulated one are two slots, because a map built on one is not a map built on the
  other, and averaging them answers neither.
* **A dataset fills as many slots as it measured.** One study that profiled both macrophage states
  fills both slots; the seven CRISPR screens fill seven fitness slots between them. The mapping is
  many-to-many in both directions, so it is written as a table rather than as a tree.

Coverage is measured, never remembered: every filled slot names the columns or the edge type that
fill it, and this script counts how many genes actually carry a value. Run it after any build.
"""
from __future__ import annotations

import csv
import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_CSV = os.path.join(_ROOT, "instructions", "done", "31_slots.csv")
OUT_MD = os.path.join(_ROOT, "instructions", "done", "31_slots.md")
OUT_TOXO_CSV = os.path.join(_ROOT, "instructions", "done", "31_slots_toxoplasma.csv")
OUT_TOXO_MD = os.path.join(_ROOT, "instructions", "done", "31_slots_toxoplasma.md")
OUT_PF_CSV = os.path.join(_ROOT, "instructions", "done", "31_slots_plasmodium.csv")
OUT_PF_MD = os.path.join(_ROOT, "instructions", "done", "31_slots_plasmodium.md")
OUT_JSON = os.path.join(_ROOT, "starplast", "data", "slots.json")
OUT_HIERARCHY_JSON = os.path.join(_ROOT, "starplast", "data", "slot_hierarchy.json")
OUT_HIERARCHY_MD = os.path.join(_ROOT, "instructions", "done", "31_slot_hierarchy.md")
CANDIDATES_JSON = os.path.join(_ROOT, "instructions", "done", "31_candidates.json")

PROSE = """# Slots: one place per question, and a choice about what fills it

**Status: complete (v0.31.0, 2026-08-14).**

**Generated by `scripts/generate_slot_table.py` -- edit the slot list there, not this file.**
Coverage is counted from the shipped cache on every run, so a number here is never a memory.

The slot catalogue and resolver landed on 2026-08-14. All six assay families previously
unreachable (`invivo_`, `stress_`, `morc_`, `proteome_`, `oocyst_`, and `phospho_`) now have their
own selectable slots and registry provenance. Searches and the analysis panel consume this table,
and the resolver applies the policy below while retaining per-gene source provenance.

## What a slot is

    slot        the question, in the map's own terms  ("how much is this gene translated")
    context     the condition it was asked under -- part of the question, not a detail
    candidates  the datasets that answer it, each with its coverage and its assay
    policy      what to do when more than one is chosen
    provenance  which dataset supplied which gene, kept per gene, not per slot

Two things follow from treating a slot as a question rather than as a dataset:

* **The condition is part of the question.** Transcription in a naive macrophage and transcription
  in an IFN-gamma-stimulated one are two slots. A map built on one is not a map built on the other,
  and averaging them answers neither.
* **A dataset fills as many slots as it measured, and a slot takes as many datasets as answer it.**
  One study profiling both macrophage states fills two slots; the seven CRISPR screens fill seven
  fitness slots between them; `rna108740_*` fills the tachyzoite and the bradyzoite slot. The
  mapping is many-to-many in both directions, which is why this is a table and not a tree.

## Why slots at all

`BLOCKS` already normalises each block to equal variance before weighting, so column count does not
decide influence today. What is missing is that a block is defined by a column-name regex -- a fact
about how a file was written -- and that nothing records that the three transcriptomes in the cache
are alternatives rather than three answers.

## The policies

| policy | what it does | when it is right |
|---|---|---|
| `one` | use the chosen dataset, ignore the rest | assays that are not comparable |
| `average` | rank-normalise each, then mean | replicates of the same measurement |
| `fill` | best-covered first, gaps from the next, source recorded per gene | the orthoLOPIT pattern |
| `separate` | keep both, sharing the slot's variance | when the disagreement is the signal |

`average` rank-normalises first because this project has already paid for that lesson: the seven
CRISPR screens differ 64-fold in spread, so a raw mean is an average of one screen. `fill` writes a
`<slot>_source` column exactly as `compartment_source` does, so an inference never reads as a
measurement.

**The circularity guard gets better, not worse.** `excluded_for` reasons about columns, datasets and
quantities today; with slots it can exclude by slot, which is what shared provenance and shared
quantity were approximating on 2026-08-13.

## Grades

**A** genome-wide and measured (>=80% of genes, or >=25% of genes for a pair-wise slot).
**B** partial (>=20%). **C** thin or indirect (<20%). **-** nothing fills it.

"""

#: Every study the table cites: PMID -> year, journal and title. Written down here rather than
#: looked up, because the table has to render on a machine with no corpus and no network --
#: and because a proposal that names a PMID without its title asks the reader to go and find
#: out what was being proposed. Titles are as PubMed gives them.
REFERENCES = {
    "21179246": ("2010", "PLoS pathogens",
               "Toxoplasma gondii lysine acetyltransferase GCN5-A functions in the cellular response "
               "to alkaline stress and expression of cyst genes."),
    "20865045": ("2010", "PLoS ONE",
               "Coordinated progression through two subtranscriptomes underlies the tachyzoite "
               "cycle of Toxoplasma gondii."),
    "24885521": ("2014", "BMC Genomics",
               "Toxoplasma gondii merozoite gene expression analysis with comparison to the life "
               "cycle discloses a unique expression state during enteric development."),
    "31167946": ("2019", "mSphere",
               "Simultaneous Ribosome Profiling of Human Host Cells Infected with Toxoplasma "
               "gondii."),
    "25757795": ("2015", "BMC genomics",
               "Asexual expansion of Toxoplasma gondii merozoites is distinct from tachyzoites and "
               "entails expression of non-overlapping gene families to attach, invade, and replicate "
               "within feline enterocytes."),
    "25867681": ("2015", "Proteomics",
               "A large-scale proteogenomics study of apicomplexan pathogens-Toxoplasma gondii and "
               "Neospora caninum."),
    "28626452": ("2017", "Frontiers in microbiology",
               "Proteomic Differences between Developmental Stages of Toxoplasma gondii Revealed by "
               "iTRAQ-Based Quantitative Proteomics."),
    "29228904": ("2017", "BMC genomics",
               "Comparative ribosome profiling uncovers a dominant role for translational control in "
               "Toxoplasma gondii."),
    "29615509": ("2018", "mBio",
               "MYR1-Dependent Effectors Are the Major Drivers of a Host Cell's Early Response to "
               "Toxoplasma, Including Counteracting MYR1-Independent Effects."),
    "29788176": ("2018", "Nucleic acids research",
               "Cooperative binding of ApiAP2 transcription factors is crucial for the expression of "
               "virulence genes in Toxoplasma gondii."),
    "31366709": ("2019", "mSphere",
               "Translocation of Dense Granule Effectors across the Parasitophorous Vacuole Membrane "
               "in Toxoplasma-Infected Cells Requires the Activity of ROP17, a Rhoptry Protein Kinase."),
    "31508380": ("2019", "Frontiers in cellular and infection microbio",
               "iTRAQ-Based Global Phosphoproteomics Reveals Novel Molecular Differences Between "
               "Toxoplasma gondii Strains of Different Genotypes."),
    "32065584": ("2020", "eLife",
               "A single-parasite transcriptional atlas of Toxoplasma Gondii reveals novel control of "
               "antigen expression."),
    "32075880": ("2020", "mSphere",
               "Coimmunoprecipitation with MYR1 Identifies Three Additional Proteins within the "
               "Toxoplasma gondii Parasitophorous Vacuole Required for Translocation of Dense Granule "
               "Effectors into Host Cells."),
    "33363051": ("2020", "Frontiers in cellular and infection microbio",
               "iTRAQ-Based Phosphoproteomic Analysis of Toxoplasma gondii Tachyzoites Provides "
               "Insight Into the Role of Phosphorylation for its Invasion and Egress."),
    "33635921": ("2021", "PLoS pathogens",
               "Protein kinase TgCDPK7 regulates vesicular trafficking and phospholipid synthesis in "
               "Toxoplasma gondii."),
    "33688018": ("2021", "mSystems",
               "Direct Nanopore Sequencing of mRNA Reveals Landscape of Transcript Isoforms in "
               "Apicomplexan Parasites."),
    "34163449": ("2021", "Frontiers in microbiology",
               "Genome-Wide CRISPR/Cas9 Screen Identifies New Genes Critical for Defense Against "
               "Oxidant Stress in Toxoplasma gondii."),
    "34263725": ("2021", "eLife",
               "A plant-like mechanism coupling m6A reading to polyadenylation safeguards "
               "transcriptome integrity and developmental gene partitioning in Toxoplasma."),
    "35164683": ("2022", "BMC genomics",
               "Genome-wide localization of histone variants in Toxoplasma gondii implicates variant "
               "exchange in stage-specific gene expression."),
    "35976251": ("2022", "eLife",
               "Temporal and thermal profiling of the Toxoplasma proteome implicates parasite Protein "
               "Phosphatase 1 in the regulation of Ca2+-responsive pathways."),
    "36214684": ("2022", "Microbiology spectrum",
               "Essential Functions of Calmodulin and Identification of Its Proximal Interacting "
               "Proteins in Tachyzoite-Stage Toxoplasma gondii via BioID Technology."),
    "36216028": ("2023", "Genomics, proteomics & bioinformatics",
               "Protein Lactylation and Metabolic Regulation of the Zoonotic Parasite Toxoplasma "
               "gondii."),
    "36916910": ("2023", "mBio",
               "CRISPR Screens Identify Toxoplasma Genes That Determine Parasite Fitness in Interferon "
               "Gamma-Stimulated Human Cells."),
    "37350586": ("2023", "mBio",
               "An apicomplexan bromodomain protein, TgBDP1, associates with diverse epigenetic "
               "factors to regulate essential transcriptional processes in Toxoplasma gondii."),
    "37562054": ("2023", "Journal of proteome research",
               "Label-free quantitative detection and comparative analysis of lysine acetylation "
               "during the different life stages of Eimeria tenella."),
    "37827122": ("2023", "Cell host & microbe",
               "High-throughput identification of Toxoplasma gondii effector proteins that target host "
               "cell transcription."),
    "37933960": ("2023", "eLife",
               "Analysis of CDPK1 targets identifies a trafficking adaptor complex that regulates "
               "microneme exocytosis in Toxoplasma."),
    "37959749": ("2023", "Molecules (Basel, Switzerland)",
               "Global Proteome-Wide Analysis of Cysteine S-Nitrosylation in Toxoplasma gondii."),
    "38093015": ("2024", "Nature",
               "In vitro production of cat-restricted Toxoplasma pre-sexual stages."),
    "38747635": ("2024", "mBio",
               "TurboID mapping reveals the exportome of secreted intrinsically disordered proteins in "
               "the transforming parasite Theileria annulata."),
    "38782906": ("2024", "Nature communications",
               "Translation initiation factor eIF1.2 promotes Toxoplasma stage conversion by "
               "regulating levels of key differentiation factors."),
    "39082802": ("2024", "mBio",
               "CRISPR screens identify genes essential for in vivo virulence among proteins of "
               "hyperLOPIT-unassigned subcellular localization in Toxoplasma."),
    "39774584": ("2024", "PLoS pathogens",
               "Cascading expression of ApiAP2 transcription factors controls daughter cell assembly "
               "in Toxoplasma gondii."),
    "39899594": ("2025", "PLoS pathogens",
               "Iron-mediated post-transcriptional regulation in Toxoplasma gondii."),
    "39912628": ("2025", "mSphere",
               "Novel antibodies detect nucleocytoplasmic O-fucose in protist pathogens, cellular "
               "slime molds, and plants."),
    "40348811": ("2025", "Communications biology",
               "Ubiquitin-activating enzyme1 (TgUAE1) acts as a key regulator of Toxoplasma gondii "
               "lytic cycle and homeostasis."),
    "40590555": ("2025", "mBio",
               "Deciphering cell cycle organization of Toxoplasma endodyogeny."),
    "40593611": ("2025", "Nature communications",
               "Regulation of the developmental programs in Toxoplasma by a novel SNF2L-containing "
               "chromatin remodeling complex."),
    "40630957": ("2025", "Frontiers in immunology",
               "Dual single-cell and bulk RNA sequencing reveal transcriptional profiles underlying "
               "heterogenous host-parasite interactions in human peripheral blood mononuclear cells."),
    "40716488": ("2025", "Journal of proteomics",
               "Quantitative proteomic analysis of the Toxoplasma gondii cytoskeleton and "
               "bioinformatic identification of highly antigenic proteins."),
    "40830525": ("2025", "Infectious diseases of poverty",
               "Cross-lineage 5-methylcytosine methylome profiling reveals methylated divergence among "
               "Toxoplasma gondii tachyzoites of the three major clonal lineages."),
    "40879678": ("2025", "mSphere",
               "GCN5a is a telomeric lysine acetyltransferase whose loss primes Toxoplasma gondii for "
               "latency."),
    "40901993": ("2025", "PLoS pathogens",
               "The PP2A-2 holoenzyme orchestrates daughter cell emergence during cytokinesis in "
               "Toxoplasma gondii."),
    "40920096": ("2025", "mSphere",
               "TgAP2X-7 is a novel cell cycle-regulated transcription factor that plays an essential "
               "role in Toxoplasma tachyzoite propagation."),
    "41137792": ("2025", "Journal of proteome research",
               "Secretome and Transcriptome Analyses Reveal New Potential Virulence Factors during "
               "Cryptosporidium parvum Invasion."),
    "41193469": ("2025", "Nature communications",
               "Toxoplasma gondii chromatin remodeler SWI/SNF controls parasite division and gene "
               "expression."),
    "41278634": ("2025", "bioRxiv : the preprint server for biology",
               "Single-cell analysis of brain-derived Toxoplasma bradyzoites reveals a novel cell "
               "cycle regulated by AP2XI-6."),
    "41580398": ("2026", "Nature communications",
               "Bradyzoite subtypes rule the crossroads of Toxoplasma development."),
    "41925342": ("2026", "mBio",
               "Global translational and metabolic remodeling during iron deprivation in Toxoplasma "
               "gondii."),
    "42020723": ("2026", "Nature microbiology",
               "A single-cell atlas of Toxoplasma sexual development in the feline intestinal tract."),
}


def _merge_candidate_references() -> dict:
    """Load proposal titles into the offline reference index, when a proposal file exists."""
    if not os.path.exists(CANDIDATES_JSON):
        return {}
    try:
        proposals = json.load(open(CANDIDATES_JSON, encoding="utf8"))
    except (OSError, ValueError):
        return {}
    for group in proposals.values():
        for proposal in group:
            pmid = str(proposal.get("pmid", ""))
            if pmid and proposal.get("title"):
                REFERENCES.setdefault(pmid, (str(proposal.get("year", "")),
                                              str(proposal.get("journal", "")),
                                              str(proposal["title"])))
    return proposals


# Rendering and tests must remain useful offline; candidate metadata is cached in the repository.
_merge_candidate_references()


#: (slot, axis, context, unit, columns/edges that fill it, suggested policy, candidates)
#: `columns` are prefixes or exact names; `edges` name a relation in graph.npz. A slot with neither
#: is empty, which is the point of listing it.
#: The organisms a slot can be about, and how to ask PubMed for one.
#:
#: The prefix is what makes two tables one table. `Tg_fitness · in vivo brain` and
#: `Pf_fitness · in vivo brain` are different questions with the same shape -- cerebral malaria and
#: cerebral toxoplasmosis are not the same disease -- and a map that averaged them would be a map
#: of neither. Prefixed, they can sit in one table, be filled independently, and be combined only
#: where a reader asks for it.
ORGANISMS = {
    "Tg": {
        "species": "Toxoplasma gondii",
        "query": ('("Toxoplasma gondii"[Title/Abstract] OR "T. gondii"[Title/Abstract] '
                  'OR Toxoplasma[Title/Abstract])'),
        "stages": "tachyzoite, bradyzoite, oocyst, merozoite",
    },
    "Pf": {
        "species": "Plasmodium falciparum",
        # berghei and vivax included on purpose: the fitness and liver-stage data that exist at
        # genome scale are largely berghei, and a slot that only accepted falciparum would be
        # permanently empty for reasons of laboratory convenience rather than biology.
        # SPECIES terms only, and `malaria` deliberately absent. A disease name is not an
        # organism: with it in the query the first pass returned red-cell physiology, endothelial
        # transporters, mosquito immunity and essential-oil antimicrobial screens -- 16 of 62
        # citations were about no parasite at all. Quoted binomials rather than bare genus words
        # for the same reason `gondii` alone would be too loose.
        "query": ('("Plasmodium falciparum"[Title/Abstract] '
                  'OR "Plasmodium berghei"[Title/Abstract] '
                  'OR "Plasmodium vivax"[Title/Abstract] '
                  'OR "Plasmodium knowlesi"[Title/Abstract] '
                  'OR "Plasmodium yoelii"[Title/Abstract] '
                  'OR "P. falciparum"[Title/Abstract] OR "P. berghei"[Title/Abstract])'),
        "stages": "ring, trophozoite, schizont, gametocyte, sporozoite, liver",
    },
}

#: How to ask for the assay behind an axis. Queries are BUILT from the slot definition rather than
#: written per slot, so a reader can see exactly why a paper was proposed and re-run the same
#: question later -- a hand-typed query is a claim nobody can check.
ASSAY_TERMS = {
    "transcription": "(RNA-seq OR transcriptome OR transcriptomic OR microarray OR scRNA-seq)",
    "translation": "(ribosome profiling OR Ribo-seq OR translatome OR polysome)",
    "protein abundance": "(proteome OR proteomic OR mass spectrometry OR quantitative proteomics)",
    "PTM": "(phosphoproteome OR acetylome OR ubiquitinome OR glycoproteome OR palmitoylome "
           "OR post-translational)",
    "fitness": "(CRISPR screen OR knockout screen OR essentiality OR fitness score "
               "OR piggyBac OR PlasmoGEM OR barcoded)",
    "regulation": "(ChIP-seq OR ATAC-seq OR chromatin OR histone OR Hi-C OR m6A OR splicing)",
    "localization": "(hyperLOPIT OR spatial proteome OR subcellular localization OR GFP tagging "
                    "OR exportome OR secretome)",
    "relation": "(interactome OR interaction OR co-immunoprecipitation OR BioID OR TurboID "
                "OR crosslinking mass spectrometry OR yeast two-hybrid)",
    "host effect": "(host response OR host transcriptome OR effector OR host-pathogen)",
    "sequence": "(genome OR domain OR ortholog OR paralog OR AlphaFold OR structure prediction)",
    "metabolism": "(metabolome OR metabolomic OR lipidome OR lipidomic OR flux)",
    "chemistry": "(chemogenomic OR drug sensitivity OR resistome OR IC50 OR compound screen)",
    "immunity": "(antigen OR seroreactivity OR epitope OR immunogenic OR vaccine candidate)",
    "phenotype": "(invasion OR egress OR motility OR plaque OR growth rate OR high-content)",
    "NEVER a feature": "",
}

#: Slots that are new in this pass, and apply to BOTH organisms. Each is a question the 71 existing
#: slots cannot express, and each is one somebody has actually measured at genome scale.
NEW_SHARED = [
    ("metabolite levels", "metabolism", "steady state", "gene", [], "separate"),
    ("metabolic flux", "metabolism", "labelled precursor", "gene", [], "separate"),
    ("lipid composition", "metabolism", "membrane lipids", "gene", [], "separate"),
    ("drug sensitivity per gene", "chemistry", "compound panel", "gene", [], "separate"),
    ("resistance-conferring mutation", "chemistry", "in vitro evolution", "gene", [], "separate"),
    ("target engagement / thermal shift", "chemistry", "thermal proteome", "gene", [], "average"),
    ("RNA-binding protein targets", "relation", "CLIP / RIP", "gene", [], "separate"),
    ("noncoding and antisense transcription", "transcription", "lncRNA", "gene", [], "separate"),
    ("codon usage / translation efficiency", "translation", "sequence-derived", "gene", [], "one"),
    ("predicted complex membership", "relation", "AlphaFold-Multimer", "gene", [], "separate"),
    ("seroreactivity / antigenicity", "immunity", "human or animal sera", "gene", [], "separate"),
    ("T-cell epitope content", "immunity", "predicted and measured", "gene", [], "average"),
    ("invasion and egress phenotype", "phenotype", "high-content imaging", "gene", [], "separate"),
    ("essentiality in a second background", "fitness", "second strain", "gene", [], "separate"),
]

#: The life-cycle stages a Plasmodium question can be asked in. Used to MIRROR the stage-bearing
#: Toxoplasma slots rather than to translate them, which is the only honest way to do it: a
#: bradyzoite is not a gametocyte and a tissue cyst is not a hypnozoite, so a slot called
#: "Pf_transcription · bradyzoite" would be a false equivalence with a plausible name. The question
#: shape carries across ("transcription, in one stage, in this host") and the stage list does not.
PF_STAGES = ("asexual blood stage", "ring", "trophozoite", "schizont", "gametocyte",
             "ookinete", "oocyst", "sporozoite", "liver stage")

#: Which axes are asked once per stage, and which are asked once with a default stage. Transcription
#: and fitness are stage-resolved because that is where the data is and where the biology differs;
#: a phosphoproteome is one question about a modification, asked in whichever stage was assayed.
PF_STAGED_AXES = ("transcription", "fitness")
PF_DEFAULT_STAGE = "asexual blood stage"

#: Fitness gets a SHORTER stage list than transcription, and the difference is not tidiness. A
#: transcriptome can be taken from any stage anyone can purify; a fitness screen needs a population
#: that can be mutated, grown, and counted, which exists for the blood stage (piggyBac in
#: falciparum, PlasmoGEM in berghei), the liver stage, and the gametocyte-to-mosquito transition.
#: Crossing fitness with the full stage list gave 37 slots against Toxoplasma's 21, including
#: "fitness in the ookinete", which nobody has measured and nobody is about to. Empty slots are
#: information, but a slot for an experiment that cannot be done is not an empty slot -- it is a
#: denominator that makes every coverage figure read low for no reason.
PF_FITNESS_STAGES = ("asexual blood stage", "liver stage", "gametocyte")

#: Toxoplasma questions with no Plasmodium counterpart at all. Listed rather than pattern-matched,
#: because "has no counterpart" is a judgement about biology and should be reviewable as one.
TOXO_ONLY_CONTEXTS = ("feline", "enteric", "cyst wall", "bradyzoite checkpoint", "brain")

#: A slot that names a PARTICULAR EXPERIMENT is not a question, and must never be mirrored. The
#: first pass got this wrong and produced `Pf_fitness · GRA12 screen 1`, `Pf_genetic interaction ·
#: delta-GRA17` and `Pf_fitness · HFF in vitro` -- GRA12 and GRA17 are Toxoplasma dense granule
#: proteins and an HFF is the fibroblast Toxoplasma is cultured in, so all three are questions about
#: one organism's laboratory wearing another organism's prefix. The distinction that matters is
#: question versus instance: "how essential is this gene in the blood stage" mirrors, "what did the
#: GRA12 screen find" does not.
#: HFF and BMDM are deliberately NOT here. They are cell types rather than studies -- the fibroblast
#: and the macrophage Toxoplasma is grown in -- so they are host CONTEXTS, and the stage expansion is
#: what handles them: "fitness in a macrophage" becomes "fitness in the asexual blood stage" rather
#: than disappearing. Listing them here deleted the blood-stage and gametocyte fitness slots, which
#: is where piggyBac and PlasmoGEM data actually live.
STUDY_SPECIFIC = ("gra1", "gra2", "delta-", "screen 1", "screen 2", "hyperlopit",
                  "ortholopit", "(young", "(sidik", "(barylyuk")


def _pf_mirror(rows):
    """The base Toxoplasma questions, asked of Plasmodium.

    Generic questions are mirrored one for one. Stage-bearing ones on a stage-resolved axis are
    re-asked once per Plasmodium stage; stage-bearing ones on any other axis are asked once, in the
    default stage. Nothing is auto-translated -- see `PF_STAGES`.
    """
    stage_words = re.compile(
        r"tachyzoite|bradyzoite|oocyst|sporozoite|merozoite|sexual|cyst|feline|enteric|brain"
        # HFF is the fibroblast Toxoplasma is cultured in and Plasmodium does not grow in one, so
        # "fitness in HFF" is a host CONTEXT to be converted, not a generic question to mirror.
        r"|macrophage|hff|bmdm", re.I)
    out, seen = [], set()
    # Dedup across everything the Pf arm ends up with, not just within this loop: `fitness · liver
    # stage` arrives both from the stage expansion and from NEW_PLASMODIUM, and two rows for one
    # question is a slot that can be half filled.
    seen.update(row[0] for row in NEW_PLASMODIUM + NEW_SHARED)
    for name, axis, context, unit, patterns, policy, candidates in rows:
        text = f"{name} {context}"
        if any(word in text.lower() for word in TOXO_ONLY_CONTEXTS):
            continue
        if any(word in text.lower() for word in STUDY_SPECIFIC):
            continue
        if not stage_words.search(text):
            if name in seen:
                continue
            seen.add(name)
            out.append((name, axis, context, unit, [], policy, []))
            continue
        question = name.split(" · ")[0]
        if axis == "fitness":
            stages = PF_FITNESS_STAGES
        elif axis in PF_STAGED_AXES:
            stages = PF_STAGES
        else:
            stages = (PF_DEFAULT_STAGE,)
        for stage in stages:
            mirrored = f"{question} · {stage}"
            if mirrored in seen:
                continue
            seen.add(mirrored)
            out.append((mirrored, axis, stage, unit, [], policy, []))
    return out


#: Malaria-specific slots: questions with no Toxoplasma counterpart, kept out of the shared list so
#: the shared list stays a statement about apicomplexan biology rather than a union of two lists.
NEW_PLASMODIUM = [
    ("transcription · liver stage", "transcription", "hepatocyte", "gene", [], "one"),
    ("transcription · mosquito stages", "transcription", "ookinete, oocyst, sporozoite", "gene",
     [], "separate"),
    ("transcription · gametocyte", "transcription", "gametocyte I-V", "gene", [], "average"),
    ("transcription · dormancy / recrudescence", "transcription", "artemisinin quiescence",
     "gene", [], "separate"),
    ("fitness · liver stage", "fitness", "hepatocyte", "gene", [], "one"),
    ("fitness · transmission", "fitness", "mosquito", "gene", [], "separate"),
    ("antigenic variation family expression", "regulation", "var / rif / stevor", "gene", [],
     "separate"),
    ("export / PEXEL trafficking", "localization", "erythrocyte cytosol", "gene", [], "one"),
    ("host receptor binding", "host effect", "endothelium, erythrocyte", "gene", [], "separate"),
    ("field variation and resistance markers", "sequence", "clinical isolates", "gene", [], "one"),
]

#: Toxoplasma-specific slots, for the same reason in the other direction.
NEW_TOXOPLASMA = [
    ("transcription · in vivo enteric", "transcription", "feline enterocyte", "gene", [], "one"),
    ("fitness · in vivo gut", "fitness", "enteric, sexual cycle", "gene", [], "separate"),
    ("cyst wall composition", "localization", "bradyzoite cyst wall", "gene", [], "separate"),
]


SLOTS = [
    # ---------------------------------------------------------------- transcription
    ("transcription · tachyzoite", "transcription", "tachyzoite, in vitro", "gene",
     ["expr_tachy", "rna108740_Tachyzoites", "invivo_TZ_", "rna22258_tachyzoite",
      "rna99395_intracellular_", "rna129869_", "rna51780_tachy_"], "one",
     []),
    ("transcription · bradyzoite / tissue cyst", "transcription", "bradyzoite", "gene",
     ["expr_cyst", "rna108740_Tissue_cysts", "rna108740_Day", "rna22258_bradyzoite"], "average",
     [("41580398", "GSE311669", "bradyzoite subtypes, 2026")]),
    ("transcription · oocyst / sporozoite", "transcription", "oocyst, sporulation", "gene",
     ["rna206344_", "expr_sporulated"], "average", []),
    ("transcription · merozoite", "transcription", "merozoite", "gene", ["rna51780_mero_"],
     "one", [("24885521", "GSE51780", "measured feline merozoites"),
              ("25757795", "PRJEB7935", "asexual expansion, distinct from tachyzoite")]),
    ("transcription · sexual stages", "transcription", "feline gut, sexual", "gene", [], "one",
     [("38093015", "GSE222819", "in vitro pre-sexual stages"),
      ("42020723", "", "single-cell atlas of sexual development, 2026")]),
    ("transcription · per cell-cycle phase", "transcription", "cell cycle", "gene",
     ["cellcycle19092_"], "separate",
     [("20865045", "GSE19092", "synchronized tachyzoite time course"),
      ("32065584", "", "the study behind cellcycle_phase, re-ingested as VALUES not a call")]),
    ("transcription · in naive macrophage", "transcription", "host: naive macrophage", "gene", [],
     "one", [("40630957", "GSE295224", "dual single-cell and bulk, host-parasite")]),
    ("transcription · in IFN-gamma macrophage", "transcription", "host: IFN-g macrophage", "gene",
     [], "one", []),
    ("transcription · in vivo brain, acute", "transcription", "mouse brain, acute", "gene",
     ["invivo_WholeBrain_Acute"], "average", []),
    ("transcription · in vivo brain, chronic", "transcription", "mouse brain, chronic", "gene",
     ["invivo_WholeBrain_Chronic"], "average", []),
    ("transcription · purified bradyzoite in vivo", "transcription",
     "mouse brain, purified bradyzoite", "gene", ["invivo_BZ_"], "average",
     [("41278634", "", "single-cell brain-derived bradyzoites, 2025")]),
    ("transcription · primary brain-cell differentiation time course", "transcription",
     "infected primary brain cells, day 1-14", "gene", ["brain168465_"], "separate", []),
    ("transcription · under stress / conversion", "transcription", "alkaline, stress", "gene",
     ["stress_"], "separate", []),
    ("transcription · extracellular lytic stress", "transcription",
     "extracellular tachyzoite", "gene", ["rna99395_extracellular_"], "separate",
     [("29228904", "GSE99395", "matched RNA for extracellular ribosome profiling")]),
    ("transcription · under TF or chromatin perturbation", "transcription", "perturbation", "gene",
     ["morc_"], "separate",
     [("39774584", "PRJNA1134678", "ApiAP2 cascade"), ("40920096", "PRJNA1281009", "AP2X-7"),
      ("41193469", "GSE287537", "SWI/SNF"), ("40879678", "GSE286088", "GCN5a"),
      ("40593611", "GSE268652", "SNF2L")]),
    ("transcription · under RNA-processing perturbation", "transcription",
     "CPSF4 depletion, tachyzoite", "gene", ["cpsf4rna168155_"], "separate",
     [("34263725", "GSE168155", "CPSF4/m6A-reader depletion RNA-seq")]),
    ("transcription · bradyzoite checkpoint perturbation", "transcription",
     "tachyzoite and bradyzoite cyclin perturbation", "gene", ["restriction200962_"],
     "separate", [("", "GSE200962", "processed count matrix; GEO has no linked publication")]),
    ("transcription · maximum observed across stages", "transcription", "cross-stage summary",
     "gene", ["expr_max"], "one", []),
    ("cell-cycle timing label", "transcription", "single-parasite atlas", "gene",
     ["cellcycle_pseudotime"], "one", []),
    ("life-cycle stage label (derived)", "transcription", "cross-stage derived target", "gene",
     ["stage_margin_derived"], "one", []),

    # ---------------------------------------------------------------- translation
    ("translation · tachyzoite", "translation", "tachyzoite, in vitro", "gene",
     ["rpf99395_intracellular_", "rpf129869_"], "separate",
     [("29228904", "GSE99395", "comparative ribosome profiling"),
      ("31167946", "GSE129869", "infected confluent/subconfluent HFFs"),
      ("38782906", "GSE245775", "eIF1.2 and stage conversion")]),
    ("translation · bradyzoite", "translation", "bradyzoite", "gene", [], "one",
     [("38782906", "GSE245775", "eIF1.2 and stage conversion")]),
    ("translation · per cell-cycle phase", "translation", "cell cycle", "gene", [], "one", []),
    ("translation · under stress", "translation", "extracellular stress or iron", "gene",
     ["rpf99395_extracellular_"], "separate",
     [("29228904", "GSE99395", "extracellular versus intracellular parasites"),
      ("41925342", "", "translational remodelling under iron starvation, 2026")]),
    ("translation efficiency · tachyzoite", "translation", "tachyzoite, in vitro", "gene",
     ["te99395_intracellular_", "te129869_"], "separate",
     [("29228904", "GSE99395", "RPF relative to matched RNA"),
      ("31167946", "GSE129869", "RPF relative to matched RNA")]),
    ("translation efficiency · extracellular stress", "translation", "extracellular stress",
     "gene", ["te99395_extracellular_"], "separate",
     [("29228904", "GSE99395", "RPF relative to matched RNA")]),

    # ---------------------------------------------------------------- protein level
    ("protein abundance · tachyzoite", "protein abundance", "tachyzoite", "gene",
     ["proteome_", "protein_ibaq_log2"], "fill",
     [("40716488", "PXD063409", "cytoskeleton proteome"),
      ("25867681", "PXD000297", "proteogenomics")]),
    ("protein abundance · other life stages", "protein abundance", "stages", "gene", ["oocyst_"],
     "separate", [("28626452", "PXD003765", "iTRAQ across developmental stages")]),
    ("protein turnover / stability", "protein abundance", "tachyzoite", "gene", [], "one",
     [("35976251", "PXD033642", "temporal and thermal proteome profiling")]),

    # ---------------------------------------------------------------- modifications
    ("phosphorylation · site count", "PTM", "tachyzoite", "gene", ["n_phosphosites", "has_phospho"],
     "one", []),
    ("phosphorylation · quantitative", "PTM", "tachyzoite", "gene", ["phospho_"], "average",
     [("33363051", "PXD020655", "iTRAQ phosphoproteome"),
      ("31508380", "PXD007777", "type I vs type II"),
      ("40901993", "PXD064226", "PP2A-2 during cytokinesis")]),
    ("phosphorylation · kinase-substrate", "PTM", "perturbation", "gene",
     [], "separate",
     [("37933960", "PXD019677", "CDPK1 substrates"), ("33635921", "PXD019655", "CDPK7")]),
    ("acetylation", "PTM", "life stages", "gene", ["n_acetylation_sites"], "one",
     [("37562054", "PXD040368", "lysine acetylation across stages")]),
    ("lactylation", "PTM", "tachyzoite", "gene", [], "one",
     [("36216028", "PXD022700", "protein lactylation")]),
    ("S-nitrosylation", "PTM", "tachyzoite", "gene", ["n_nitrosylation_sites"], "one",
     [("37959749", "PXD046083", "proteome-wide cysteine S-nitrosylation")]),
    ("ubiquitination / SUMOylation", "PTM", "tachyzoite", "gene",
     ["n_ubiquitination_sites"], "one",
     [("40348811", "PXD045018", "TgUAE1"), ("40590555", "PXD054719", "endodyogeny")]),
    ("glycosylation", "PTM", "tachyzoite", "gene", [], "one",
     [("39912628", "PXD056853", "nucleocytoplasmic O-fucose")]),
    ("palmitoylation", "PTM", "tachyzoite", "gene", [], "one", []),

    # ---------------------------------------------------------------- fitness
    ("fitness · HFF in vitro", "fitness", "HFF", "gene", ["fit_invitro_hff"], "one", []),
    ("fitness · naive macrophage", "fitness", "naive BMDM", "gene", ["fit_naive_bmdm"], "one", []),
    ("fitness · IFN-gamma macrophage", "fitness", "IFN-g BMDM", "gene", ["fit_ifng"], "one",
     [("36916910", "", "a second IFN-gamma screen")]),
    ("fitness · in vivo peritoneum", "fitness", "mouse peritoneum", "gene", ["fit_invivo_PE"],
     "one", []),
    ("fitness · in vivo lung", "fitness", "mouse lung", "gene", ["fit_invivo_lung"], "one", []),
    ("fitness · in vivo liver", "fitness", "mouse liver", "gene", ["fit_invivo_liver"], "one", []),
    ("fitness · in vivo spleen", "fitness", "mouse spleen", "gene", ["fit_invivo_spleen"], "one",
     []),
    ("fitness · oxidative stress", "fitness", "oxidant", "gene", [], "one",
     [("34163449", "PRJNA707360", "genome-wide oxidative-stress screen")]),
    ("fitness · hyperLOPIT-unassigned proteins", "fitness", "in vivo virulence", "gene",
     ["fit_hyperlopit_unassigned_invivo_"], "separate",
     [("39082802", "GSE253884", "aimed at this map's largest gap")]),
    ("fitness · targeted in vivo (Young 2019)", "fitness", "mouse, targeted libraries", "gene",
     ["fit_invivo_young2019", "crispr_invivo_platform_lfc"], "separate", []),
    ("genetic interaction · delta-GRA17", "fitness", "GRA17 background", "gene",
     ["crispr_gra17"], "one", []),
    ("fitness · GRA12 screen 1 in vitro", "fitness", "GRA12 screen 1, in vitro", "gene",
     ["crispr_gra12s1_l2fc_invitro"], "one", []),
    ("fitness · GRA12 screen 1 in vivo", "fitness", "GRA12 screen 1, mouse", "gene",
     ["crispr_gra12s1_l2fc_invivo"], "one", []),
    ("fitness · GRA12 screen 1 differential", "fitness", "GRA12 screen 1, in vivo vs in vitro",
     "gene", ["crispr_gra12s1_disco"], "one", []),
    ("fitness · GRA12 screen 2 in vitro", "fitness", "GRA12 screen 2, in vitro", "gene",
     ["crispr_gra12s2_l2fc_invitro"], "one", []),
    ("fitness · GRA12 screen 2 in vivo", "fitness", "GRA12 screen 2, mouse", "gene",
     ["crispr_gra12s2_l2fc_invivo"], "one", []),
    ("fitness · GRA12 screen 2 differential", "fitness", "GRA12 screen 2, in vivo vs in vitro",
     "gene", ["crispr_gra12s2_disco"], "one", []),
    ("stage-conversion phenotype", "fitness", "bradyzoite conversion", "gene", ["diff_reporter_log2_mNG_over_bulk"], "one", []),
    ("drug sensitivity", "fitness", "compound", "gene", [], "separate", []),

    # ---------------------------------------------------------------- regulation
    ("TF binding · per factor", "regulation", "ChIP / CUT&RUN", "gene", [], "separate",
     [("29788176", "GSE106864", "ApiAP2 cooperative binding"),
      ("37350586", "GSE228853", "BDP1 bromodomain")]),
    ("chromatin state · histone marks", "regulation", "tachyzoite / bradyzoite", "gene", [], "fill",
     [("35164683", "GSE104347", "histone variants genome-wide"),
      ("21179246", "GSE22100", "GCN5-A under alkaline stress")]),
    ("chromatin accessibility", "regulation", "stages", "gene", [], "one",
     [("38093015", "PRJNA921935", "pre-sexual stages")]),
    ("RNA modification · m6A / 5mC", "regulation", "tachyzoite", "gene", [], "separate",
     [("34263725", "GSE168155", "m6A reader and polyadenylation"),
      ("40830525", "GSE294543", "5mC methylome across lineages")]),
    ("splicing / isoform use", "regulation", "stages", "gene", [], "one",
     [("33688018", "PRJNA606986", "nanopore isoform landscape")]),
    ("RNA stability / half-life", "regulation", "tachyzoite", "gene", [], "one",
     [("39899594", "PRJEB67890", "iron-mediated post-transcriptional regulation")]),

    # ---------------------------------------------------------------- localisation and exposure
    ("localization · measured", "localization", "hyperLOPIT", "gene",
     ["compartment", "compartment_source", "lopit_prob", "lopit_methods_agree",
      "lopit_confident"], "one", []),
    ("localization · transferred", "localization", "orthoLOPIT", "gene",
     ["ortholopit_", "compartment_best"], "fill", []),
    ("membrane topology", "localization", "sequence", "gene",
     ["dtm_class", "n_tm", "has_signal_peptide", "is_tm", "tm_kd_", "tm_len_mean"], "one", []),
    ("exposure to host cytosol", "localization", "PVM, export", "gene", [], "fill",
     [("38747635", "", "TurboID exportome of secreted disordered proteins"),
      ("29615509", "GSE109830", "MYR1-dependent effectors"),
      ("31366709", "GSE122786", "translocation across the PVM")]),
    ("secretome / excreted", "localization", "ESA", "gene", [], "one",
     [("41137792", "PXD028969", "secretome and transcriptome")]),

    # ---------------------------------------------------------------- relations (gene pairs)
    ("co-transcription", "relation", "stage series", "pair", ["edge:coexpression"], "separate", []),
    ("co-translation", "relation", "ribosome profiling", "pair", [], "separate", []),
    ("co-fitness", "relation", "seven screens", "pair", ["edge:cofitness"], "separate", []),
    ("interaction · crosslink MS", "relation", "measured contact", "pair", ["edge:xlms"], "one",
     []),
    ("interaction · IP-MS, parasite-parasite", "relation", "pulldown", "pair", ["edge:ip_ms"],
     "fill", [("", "", "55 IP-MS studies already downloaded and not curated")]),
    ("interaction · proximity labelling", "relation", "BioID / TurboID", "gene",
     ["n_proximity_partners"], "fill",
     [("", "", "44 BioID studies already downloaded"),
      ("36214684", "PXD032102", "calmodulin proximal interactors")]),
    ("interaction · structural similarity", "relation", "Foldseek", "pair", ["edge:struct"], "one",
     []),
    ("interaction · with host proteins", "relation", "host IP-MS", "pair", [], "separate",
     [("32075880", "PXD016383", "MYR1 co-IP"), ("38747635", "", "exportome TurboID")]),
    ("shared compartment", "relation", "hyperLOPIT", "pair", ["edge:compartment"], "one", []),
    ("shared orthogroup", "relation", "OrthoMCL", "pair", ["edge:orthogroup"], "one", []),
    ("shared domain", "relation", "InterPro", "pair", ["edge:domain"], "one", []),
    ("interaction degree · crosslink MS", "relation", "measured contact", "gene",
     ["n_xlink_partners", "best_model_agreement"], "separate", []),
    ("interaction degree · IP-MS", "relation", "curated pulldown", "gene",
     ["n_ipms_partners"], "one", []),
    ("interaction degree · structural similarity", "relation", "Foldseek", "gene",
     ["n_struct_similar"], "one", []),
    ("host interaction degree", "host effect", "curated parasite-host interactions", "gene",
     ["n_host_targets"], "one", []),
    ("downloaded-study membership", "NEVER a feature", "BioID / IP-MS corpus coverage", "gene",
     ["n_bioid_studies", "n_ipms_studies"], "separate", []),
    ("analysis-derived structural holes", "NEVER a feature", "coexpression + cofitness - literature",
     "gene", ["n_holes"], "one", []),
    ("assay confidence and significance", "NEVER a feature", "target evidence metadata", "gene",
     ["hosttx_padj"], "one", []),

    # ---------------------------------------------------------------- host effect
    ("host transcriptional effect per effector", "host effect", "dual perturb-seq", "gene",
     ["hosttx_T2", "hosttx_signature_"], "separate",
     [("37827122", "GSE229505", "the per-effector host signature, not just its p-value")]),

    # ---------------------------------------------------------------- sequence and conservation
    ("domain content", "sequence", "InterPro", "gene",
     ["n_interpro", "has_domain", "interpro_id", "interpro_desc", "pfam_id"], "one", []),
    ("fold confidence / disorder", "sequence", "AlphaFold", "gene", ["mean_plddt", "has_structure"],
     "one", []),
    ("conservation breadth", "sequence", "OrthoMCL", "gene",
     ["has_pf_ortholog", "has_cp_ortholog", "lineage_specific", "orthogroup"], "one", []),
    ("paralogy", "sequence", "OrthoMCL", "gene", ["paralog_number"], "one", []),
    ("sequence basics", "sequence", "protein", "gene", ["length", "sequence"], "one", []),
    ("strain variation", "sequence", "population", "gene", [], "one", []),

    # ---------------------------------------------------------------- not a feature
    ("literature attention", "NEVER a feature", "PubMed / PMC", "gene",
     ["n_publications", "n_fulltext", "n_papers_", "attention_depth", "lit_tier"], "one", []),
    ("gene identity and annotation", "NEVER a feature", "ToxoDB", "gene",
     ["gene_id", "product"], "one", []),
]


def _slug(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", str(text).lower()).strip("_")


# A slot has three parents because three different questions must not be conflated:
#   evidence: what kind of observation is this?
#   biology:  what biological subject does it inform?
#   context:  in what system/condition was it observed?
# The leaves are still slots; these paths only provide independently selectable groupings above them.
EVIDENCE_PATHS = {
    "transcription": ("molecular measurements", "RNA", "transcript abundance"),
    "translation": ("molecular measurements", "translation", "ribosome occupancy"),
    "protein abundance": ("molecular measurements", "protein", "abundance"),
    "PTM": ("molecular measurements", "protein", "post-translational state"),
    "fitness": ("perturbational measurements", "genetic screens", "fitness"),
    "regulation": ("molecular measurements", "regulation", "chromatin and RNA regulation"),
    "localization": ("molecular measurements", "spatial biology", "localization"),
    "relation": ("relational measurements", "gene-gene", "association or interaction"),
    "host effect": ("relational measurements", "parasite-host", "host effect"),
    "sequence": ("intrinsic and reference", "sequence and evolution", "gene attributes"),
    "metabolism": ("molecular measurements", "metabolism", "metabolite or flux"),
    "chemistry": ("perturbational measurements", "chemical", "response or engagement"),
    "immunity": ("relational measurements", "host immunity", "recognition"),
    "phenotype": ("perturbational measurements", "cell phenotype", "imaging phenotype"),
    "NEVER a feature": ("metadata and derived outputs", "excluded from embeddings"),
}

BIOLOGY_PATHS = {
    "transcription": ("gene expression", "RNA abundance"),
    "translation": ("gene expression", "protein synthesis"),
    "protein abundance": ("gene expression", "protein abundance"),
    "PTM": ("protein state", "post-translational modification"),
    "fitness": ("parasite phenotype", "fitness and essentiality"),
    "regulation": ("gene regulation",),
    "localization": ("cell organization", "localization and topology"),
    "relation": ("molecular relationships", "parasite-parasite"),
    "host effect": ("molecular relationships", "parasite-host"),
    "sequence": ("intrinsic properties", "sequence structure and evolution"),
    "metabolism": ("metabolism",),
    "chemistry": ("parasite phenotype", "chemical response"),
    "immunity": ("host recognition",),
    "phenotype": ("parasite phenotype", "cellular process"),
    "NEVER a feature": ("provenance and analysis metadata",),
}


def _context_path(context: str) -> tuple:
    """Coarse experimental-system tree; exact context remains on the slot itself."""
    low = context.lower()
    if any(word in low for word in ("mouse", "brain", "feline", "enteric", "in vivo")):
        system = "in vivo"
    elif any(word in low for word in ("macrophage", "hff", "host", "neuron", "erythrocyte",
                                      "hepatocyte", "sera")):
        system = "host-cell or host-derived"
    elif any(word in low for word in ("sequence", "orthomcl", "interpro", "alphafold",
                                      "foldseek", "protein")):
        system = "reference or computational"
    else:
        system = "in vitro or assay-defined"
    stage = next((stage for stage in ("tachyzoite", "bradyzoite", "oocyst", "sporozoite",
                                      "merozoite", "sexual", "gametocyte", "liver stage")
                  if stage in low), "stage-unspecified")
    return (system, stage)


# Explicit outcomes and same-quantity families drive leakage closure.  A family is intentionally
# narrower than a biological domain: sequence-derived membrane topology is useful evidence for a
# held-out localization label, not a restatement of that label.
SLOT_OVERRIDES = {
    "localization · measured": {
        "target_family": "subcellular localization",
        "target_columns": ["compartment", "lopit_map", "lopit_mcmc", "lopit_unified"],
    },
    "localization · transferred": {
        "evidence_path": ["intrinsic and reference", "orthology-derived", "localization transfer"],
        "target_family": "subcellular localization",
        "target_columns": ["compartment_best", "ortholopit_label", "ortholopit_accepted"],
    },
    "exposure to host cytosol": {"target_family": "subcellular localization"},
    "secretome / excreted": {"target_family": "subcellular localization"},
    "cyst wall composition": {"target_family": "subcellular localization"},
    "shared compartment": {"target_family": "subcellular localization"},
    "cell-cycle timing label": {
        "target_family": "cell-cycle timing",
        "target_columns": ["cellcycle_phase", "cellcycle_pseudotime"], "role": "target",
    },
    "life-cycle stage label (derived)": {
        "evidence_path": ["metadata and derived outputs", "derived target labels", "life-cycle stage"],
        "target_family": "life-cycle stage",
        "target_columns": ["stage_enriched_derived", "stage_margin_derived"], "role": "target",
    },
    "literature attention": {
        "target_family": "literature attention",
        "target_columns": ["attention_depth", "lit_tier"], "role": "never",
    },
    "downloaded-study membership": {"role": "metadata"},
    "analysis-derived structural holes": {"role": "never"},
    "assay confidence and significance": {"role": "metadata"},
    "gene identity and annotation": {"role": "metadata"},
    # This is sequence evidence whose biological subject is localisation.  It must not be placed
    # under the LOPIT assay branch: doing so would remove a legitimate predictor in the ordinary
    # measured-localisation holdout.
    "membrane topology": {
        "evidence_path": ["intrinsic and reference", "sequence-derived", "membrane topology"],
        "target_family": "membrane topology",
    },
}


def _definition(row, organism: str) -> dict:
    """Either slot tuple shape as one serializable definition."""
    if len(row) == 6:
        name, axis, context, unit, fills, policy = row
        candidates = []
    else:
        name, axis, context, unit, fills, policy, candidates = row
    override = SLOT_OVERRIDES.get(name, {})
    role = override.get("role", "never" if axis == "NEVER a feature" else "feature")
    evidence = override.get("evidence_path", EVIDENCE_PATHS.get(axis, ("other", axis)))
    biology = override.get("biology_path", BIOLOGY_PATHS.get(axis, ("other", axis)))
    return {"organism": organism, "name": name, "axis": axis, "context": context,
            "unit": unit, "patterns": list(fills), "policy": policy,
            "candidates": list(candidates), "evidence_path": list(evidence),
            "biology_path": list(biology), "context_path": list(_context_path(context)),
            "target_family": str(override.get("target_family", _slug(name))),
            "target_columns": list(override.get("target_columns", ())), "role": role}


def all_slots(organism: str | None = None) -> list:
    """The Toxoplasma, Plasmodium, or combined catalog with organism prefixes explicit."""
    toxo = ([_definition(row, "Tg") for row in SLOTS]
            + [_definition(row, "Tg") for row in NEW_SHARED + NEW_TOXOPLASMA])
    pf = ([_definition(row, "Pf") for row in _pf_mirror(SLOTS)]
          + [_definition(row, "Pf") for row in NEW_SHARED]
          + [_definition(row, "Pf") for row in NEW_PLASMODIUM])
    out = toxo + pf
    if organism:
        out = [row for row in out if row["organism"] == organism]
    if os.path.exists(CANDIDATES_JSON):
        proposals = _merge_candidate_references()
        for row in out:
            key = f"{row['organism']}::{row['name']}"
            for proposal in proposals.get(key, []):
                pmid = str(proposal.get("pmid", ""))
                candidate = (pmid, str(proposal.get("accession", "")),
                             str(proposal.get("note") or proposal.get("title", "")))
                if candidate not in row["candidates"]:
                    row["candidates"].append(candidate)
    return out


def coverage(nodes, patterns):
    """How many genes carry a value in the columns this slot is filled by."""
    cols = []
    for pattern in patterns:
        matches = [pattern] if pattern in nodes.columns else [
            c for c in nodes.columns if c.startswith(pattern)]
        cols.extend(c for c in matches if c not in cols)
    if not cols:
        return 0, []
    return int(nodes[cols].notna().any(axis=1).sum()), cols


def grade(frac: float, filled: bool, unit: str) -> str:
    """A for genome-wide and measured, B for partial, C for thin or indirect, - for empty."""
    if not filled:
        return "-"
    if unit == "pair":
        return "A" if frac >= 0.25 else ("B" if frac >= 0.05 else "C")
    return "A" if frac >= 0.8 else ("B" if frac >= 0.2 else "C")


def _cited(row) -> str:
    """The candidates for one slot, each as its title, year and accession -- not a bare PMID.

    A proposal that names an identifier and nothing else asks the reader to go and look up what is
    being proposed, which is most of the work of reading a list like this.
    """
    out = []
    for token in (row["candidates"] or "").split(";"):
        token = token.strip()
        if not token:
            continue
        if not token.startswith("PMID "):
            out.append(token)
            continue
        parts = token.split()
        pmid = parts[1]
        rest = " ".join(parts[2:])
        acc = rest.split("(")[0].strip()
        year, journal, title = REFERENCES.get(pmid, ("", "", ""))
        link = f"[{pmid}](https://pubmed.ncbi.nlm.nih.gov/{pmid}/)"
        bits = [f"**{title}**" if title else "", f"({journal} {year})".strip() if journal else year,
                link, f"`{acc}`" if acc else ""]
        out.append(" ".join(b for b in bits if b))
    return "<br>".join(out)


def _write_markdown(rows, path=OUT_MD) -> None:
    """The same table, rendered. One file to read, one file to compute with."""
    by_axis = {}
    for r in rows:
        by_axis.setdefault(r["axis"], []).append(r)
    lines = [PROSE]
    counts = {g: sum(1 for r in rows if r["grade"] == g) for g in ("A", "B", "C", "-")}
    lines.append(f"**{len(rows)} slots: {counts['A']} covered well, {counts['B']} partly, "
                 f"{counts['C']} thinly, {counts['-']} empty.**\n")
    for axis, group in by_axis.items():
        lines.append(f"### {axis}\n")
        lines.append("| slot | context | grade | genes | coverage | filled by | policy | "
                     "candidates to fill or improve it |")
        lines.append("|---|---|---|---|---|---|---|---|")
        for r in group:
            lines.append(f"| {r['slot']} | {r['context']} | **{r['grade']}** | "
                         f"{r['genes'] or ''} | {r['coverage']} | `{r['filled_by']}` | "
                         f"{r['policy']} | {_cited(r) or '—'} |")
        lines.append("")

    # One dataset, several slots -- the many-to-many, read off the table itself.
    shared = {}
    for r in rows:
        for token in (r["candidates"] or "").split(";"):
            token = token.strip()
            if token.startswith("PMID "):
                pmid = token.split()[1]
                shared.setdefault(pmid, []).append(r["slot"])
    multi = {p: s for p, s in shared.items() if len(s) > 1}
    for r in rows:
        for col in r["filled_by"].split(", "):
            if col and not col.startswith("edge:"):
                shared.setdefault(col, []).append(r["slot"])
    multi_cols = {c: s for c, s in shared.items()
                  if len(s) > 1 and not c.isdigit()}
    if multi or multi_cols:
        lines.append("### One dataset, several slots\n")
        lines.append("Read off the table above: this is the many-to-many the mechanism has to "
                     "carry, not a special case.\n")
        lines.append("| dataset or column family | slots it fills |")
        lines.append("|---|---|")
        for key, slots in list(multi.items()) + list(multi_cols.items()):
            name = (f"[PMID {key}](https://pubmed.ncbi.nlm.nih.gov/{key}/)" if key.isdigit()
                    else f"`{key}`")
            lines.append(f"| {name} | {'; '.join(sorted(set(slots)))} |")
        lines.append("")
    open(path, "w", encoding="utf8").write("\n".join(lines))


def _rows(definitions, nodes, graph) -> list:
    """Definitions with measured cache coverage attached."""
    import numpy as np
    n_genes, rows = len(nodes), []
    for definition in definitions:
        slot, axis = definition["name"], definition["axis"]
        context, unit = definition["context"], definition["unit"]
        fills, policy, cands = definition["patterns"], definition["policy"], definition["candidates"]
        edges = [value[len("edge:"):] for value in fills if value.startswith("edge:")]
        columns = [value for value in fills if not value.startswith("edge:")]
        if edges:
            key = f"{edges[0]}__a"
            pairs = int(len(graph[key])) if key in graph.files else 0
            covered = int(len(set(np.concatenate([graph[f"{edges[0]}__a"],
                                                   graph[f"{edges[0]}__b"]])))) if key in graph.files else 0
            detail = f"{pairs:,} pairs"
        elif definition["organism"] == "Tg":
            covered, cols = coverage(nodes, columns)
            detail = f"{len(cols)} columns" if cols else ""
        else:
            covered, cols, detail = 0, [], ""
        frac = covered / n_genes if n_genes else 0.0
        rows.append({
            "organism": definition["organism"],
            "slot": f"{definition['organism']}_{slot}", "axis": axis, "context": context,
            "unit": unit, "grade": grade(frac, bool(covered), unit), "genes": covered,
            "coverage": f"{frac:.1%}" if covered else "",
            "filled_by": ", ".join(edges or columns), "detail": detail, "policy": policy,
            "candidates": "; ".join(f"PMID {p} {a}".strip() + (f" ({note})" if note else "")
                                    for p, a, note in cands),
            "candidate_titles": " | ".join(
                f"{p}: {REFERENCES.get(p, ('', '', note))[2]}" if p else note
                for p, a, note in cands),
        })
    return rows


def _write_csv(rows, path) -> None:
    """Write one reproducible LF-delimited slot table."""
    with open(path, "w", newline="", encoding="utf8") as fh:
        writer = csv.DictWriter(fh, fieldnames=list(rows[0]), lineterminator="\n")
        writer.writeheader()
        writer.writerows(rows)


def _nested_tree(definitions: list, facet: str, organism: str) -> dict:
    """Build one hierarchy facet without importing the generated runtime catalogue."""
    out = {}
    for row in definitions:
        if row["organism"] != organism:
            continue
        key = f"{organism}_{_slug(row['name'])}"
        branch = out
        for part in tuple(row[f"{facet}_path"]) + (key,):
            branch = branch.setdefault(part, {})
    return out


def _tree_lines(tree: dict, depth: int = 0) -> list:
    lines = []
    for key, child in tree.items():
        lines.append(f"{'  ' * depth}- {key}")
        lines.extend(_tree_lines(child, depth + 1))
    return lines


def _write_hierarchy(definitions: list) -> None:
    trees = {organism: {facet: _nested_tree(definitions, facet, organism)
                        for facet in ("evidence", "biology", "context")}
             for organism in ("Tg", "Pf")}
    with open(OUT_HIERARCHY_JSON, "w", encoding="utf8") as fh:
        json.dump(trees, fh, indent=2, ensure_ascii=False)
        fh.write("\n")
    lines = ["# Slot relationship hierarchy", "",
             "Slots are the leaves of three independent trees. A single tree would create false "
             "relationships: for example, membrane topology is sequence evidence about localization, "
             "and a stage RNA-seq experiment also has an in-vivo or in-vitro context.", "",
             "- **Evidence** controls assay/data-class holdouts: what kind of observation was made.",
             "- **Biology** groups the subject being inferred or interpreted.",
             "- **Context** groups the experimental system and stage.",
             "- **Provenance and derivation are a graph, not a tree.** Dataset registry entries and "
             "`derived_from` edges provide the closure used by leakage exclusion.", ""]
    for facet in ("evidence", "biology", "context"):
        lines.extend((f"## Toxoplasma — {facet}", "", *_tree_lines(trees["Tg"][facet]), ""))
    open(OUT_HIERARCHY_MD, "w", encoding="utf8").write("\n".join(lines))


def main() -> int:
    import numpy as np
    import pandas as pd
    from starplast import paths

    nodes = pd.read_parquet(paths.cache_file("nodes.parquet"))
    z = np.load(paths.cache_file("graph.npz"), allow_pickle=True)
    definitions = all_slots()
    rows = _rows(definitions, nodes, z)
    toxo_rows = [row for row in rows if row["organism"] == "Tg"]
    pf_rows = [row for row in rows if row["organism"] == "Pf"]
    os.makedirs(os.path.dirname(OUT_CSV), exist_ok=True)
    for subset, csv_path, md_path in ((rows, OUT_CSV, OUT_MD),
                                      (toxo_rows, OUT_TOXO_CSV, OUT_TOXO_MD),
                                      (pf_rows, OUT_PF_CSV, OUT_PF_MD)):
        _write_csv(subset, csv_path)
        _write_markdown(subset, md_path)
    with open(OUT_JSON, "w", encoding="utf8") as fh:
        json.dump(definitions, fh, indent=2, ensure_ascii=False)
        fh.write("\n")
    _write_hierarchy(definitions)
    empty = sum(1 for r in rows if r["grade"] == "-")
    print(f"{len(rows)} slots -> combined, Toxoplasma and Plasmodium tables")
    print(f"  A {sum(1 for r in rows if r['grade'] == 'A')}   "
          f"B {sum(1 for r in rows if r['grade'] == 'B')}   "
          f"C {sum(1 for r in rows if r['grade'] == 'C')}   empty {empty}")
    return len(rows)


if __name__ == "__main__":
    main()
