#!/usr/bin/env python3
"""The question table: what this data can be asked, what it cannot, and which verdicts were measured.

One row per candidate question from `starplast/data/questions.json`, each run through the real
leakage closure against the shipped cache. The document and the program therefore cannot drift: the
same `recipes.close` that refuses a question at run time is what marks it undeliverable here.

The dropped questions are the point of the document as much as the kept ones. A question dropped for
"the holdout has 221 labelled genes and a cluster needs 15 before it can be evaluated" is not a
failure -- it is an acquisition target, stated precisely enough to act on, exactly as the empty
slots' `blocked_by` verdicts are.

Run after any build: `python scripts/generate_question_table.py`
"""
from __future__ import annotations

import os
import sys

import pandas as pd

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_CSV = os.path.join(_ROOT, "instructions", "done", "45_questions.csv")
OUT_MD = os.path.join(_ROOT, "instructions", "done", "45_questions.md")
NODES = os.path.join(_ROOT, "starplast", "data", "nodes.parquet")


def render(table: pd.DataFrame, questions: list) -> str:
    """The table as a document, kept questions first and the drops grouped by what blocked them."""
    from starplast.questions import AXES
    kept = table[table.shipped & table.closure_ok]
    covered = table[table.declared.eq("keep") & table.closure_ok & ~table.shipped]
    lines = [
        "# 45 — a hundred questions, and the ones worth shipping",
        "",
        "Generated by `scripts/generate_question_table.py`. **Every verdict below is measured, not",
        "asserted:** each question is run through `recipes.close` against the shipped cache, and a",
        "question its author kept that closure refuses is dropped with the closure's own words.",
        "",
        f"**{len(table)} candidates · {len(kept)} shipped · {len(covered)} sound but covered · "
        f"{int(table.declared.eq('uncertain').sum())} uncertain · "
        f"{int(table.declared.eq('drop').sum())} dropped**",
        "",
        "One question per DISTINCT holdout. Twenty recipes predicting the same label from twenty",
        "input sets is one recipe run twenty times, so a sound question whose label another shipped",
        "question already holds out is kept in the file and marked covered rather than offered.",
        "",
        "## The twenty shipped questions",
        "",
        "| # | axis | question | holdout (labelled) | control | inputs |",
        "|---|---|---|---|---|---|",
    ]
    for i, (_, r) in enumerate(kept.iterrows(), 1):
        lines.append(f"| {i} | {r.axis} | {r.question} | `{r.holdout}` ({r.holdout_labelled:,}) | "
                     f"{'`' + r.control + '`' if r.control else '—'} | {r.blocks} blocks, "
                     f"{r.columns} columns |")
    lines += ["", "## Sound, but a shipped question already holds out that label", ""]
    for _, r in covered.iterrows():
        lines.append(f"* **{r.question}** — holdout `{r.holdout}`")
    lines += ["", "## What was dropped, and what would fix it", ""]
    for axis in list(AXES) + [""]:
        rows = table[(table.axis == axis) & (~table.shipped) & (~table.declared.eq("keep")
                                                                | ~table.closure_ok)]
        if not len(rows):
            continue
        lines += [f"### {axis or 'unassigned'}", ""]
        for _, r in rows.iterrows():
            why = r.refusal or r.reason
            flag = " **[shipped anyway, as a deliberate failure]**" if r.expect_refusal else ""
            lines.append(f"* **{r.question}** — {why}{flag}")
        lines.append("")
    return "\n".join(lines) + "\n"


def main() -> int:
    from starplast.questions import load, verify
    questions = load()
    if not questions:
        print("no questions in starplast/data/questions.json"); return 1
    if not os.path.exists(NODES):
        print("no built node table; run python -m starplast.build_graph first"); return 1
    nodes = pd.read_parquet(NODES)
    table = verify(nodes, questions)
    table.to_csv(OUT_CSV, index=False)
    with open(OUT_MD, "w") as fh:
        fh.write(render(table, questions))
    kept = int((table.shipped & table.closure_ok).sum())
    disagreed = int((table.declared.eq("keep") & ~table.closure_ok).sum())
    print(f"{len(table)} questions -> {OUT_CSV}")
    print(f"  shipped: {kept}")
    print(f"  kept by their author but REFUSED by closure: {disagreed}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
