#!/usr/bin/env python3
"""The slot table: one row per question the map can ask, graded against the shipped cache.

A slot is a QUESTION -- "how much is this gene transcribed in an IFN-gamma-stimulated macrophage" --
not a dataset and not a column family. Two consequences, and both are why this file exists rather
than a paragraph of prose:

* **The condition is part of the question.** Transcription in a naive macrophage and transcription
  in an IFN-gamma-stimulated one are two slots, because a map built on one is not a map built on the
  other, and averaging them answers neither.
* **A dataset fills as many slots as it measured.** One study that profiled both macrophage states
  fills both slots; the seven CRISPR screens fill seven fitness slots between them. The mapping is
  many-to-many in both directions, so it is written as a table rather than as a tree.

Coverage is measured, never remembered: every filled slot names the columns or the edge type that
fill it, and this script counts how many genes actually carry a value. Run it after any build.
"""
from __future__ import annotations

import csv
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_CSV = os.path.join(_ROOT, "instructions", "open", "31_slots.csv")
OUT_MD = os.path.join(_ROOT, "instructions", "open", "31_slots.md")

PROSE = """# Slots: one place per question, and a choice about what fills it

**Generated by `scripts/generate_slot_table.py` -- edit the slot list there, not this file.**
Coverage is counted from the shipped cache on every run, so a number here is never a memory.

## What a slot is

    slot        the question, in the map's own terms  ("how much is this gene translated")
    context     the condition it was asked under -- part of the question, not a detail
    candidates  the datasets that answer it, each with its coverage and its assay
    policy      what to do when more than one is chosen
    provenance  which dataset supplied which gene, kept per gene, not per slot

Two things follow from treating a slot as a question rather than as a dataset:

* **The condition is part of the question.** Transcription in a naive macrophage and transcription
  in an IFN-gamma-stimulated one are two slots. A map built on one is not a map built on the other,
  and averaging them answers neither.
* **A dataset fills as many slots as it measured, and a slot takes as many datasets as answer it.**
  One study profiling both macrophage states fills two slots; the seven CRISPR screens fill seven
  fitness slots between them; `rna108740_*` fills the tachyzoite and the bradyzoite slot. The
  mapping is many-to-many in both directions, which is why this is a table and not a tree.

## Why slots at all

`BLOCKS` already normalises each block to equal variance before weighting, so column count does not
decide influence today. What is missing is that a block is defined by a column-name regex -- a fact
about how a file was written -- and that nothing records that the three transcriptomes in the cache
are alternatives rather than three answers.

## The policies

| policy | what it does | when it is right |
|---|---|---|
| `one` | use the chosen dataset, ignore the rest | assays that are not comparable |
| `average` | rank-normalise each, then mean | replicates of the same measurement |
| `fill` | best-covered first, gaps from the next, source recorded per gene | the orthoLOPIT pattern |
| `separate` | keep both, sharing the slot's variance | when the disagreement is the signal |

`average` rank-normalises first because this project has already paid for that lesson: the seven
CRISPR screens differ 64-fold in spread, so a raw mean is an average of one screen. `fill` writes a
`<slot>_source` column exactly as `compartment_source` does, so an inference never reads as a
measurement.

**The circularity guard gets better, not worse.** `excluded_for` reasons about columns, datasets and
quantities today; with slots it can exclude by slot, which is what shared provenance and shared
quantity were approximating on 2026-08-13.

## Grades

**A** genome-wide and measured (>=80% of genes, or >=25% of genes for a pair-wise slot).
**B** partial (>=20%). **C** thin or indirect (<20%). **-** nothing fills it.

"""

#: (slot, axis, context, unit, columns/edges that fill it, suggested policy, candidates)
#: `columns` are prefixes or exact names; `edges` name a relation in graph.npz. A slot with neither
#: is empty, which is the point of listing it.
SLOTS = [
    # ---------------------------------------------------------------- transcription
    ("transcription · tachyzoite", "transcription", "tachyzoite, in vitro", "gene",
     ["expr_tachy", "rna108740_Tachyzoites"], "one",
     []),
    ("transcription · bradyzoite / tissue cyst", "transcription", "bradyzoite", "gene",
     ["expr_cyst", "rna108740_Tissue_cysts", "rna108740_Day"], "average",
     [("41580398", "GSE311669", "bradyzoite subtypes, 2026")]),
    ("transcription · oocyst / sporozoite", "transcription", "oocyst, sporulation", "gene",
     ["rna206344_", "expr_sporulated"], "average", []),
    ("transcription · merozoite", "transcription", "merozoite", "gene", [], "one",
     [("25757795", "PRJEB7935", "asexual expansion, distinct from tachyzoite")]),
    ("transcription · sexual stages", "transcription", "feline gut, sexual", "gene", [], "one",
     [("38093015", "GSE222819", "in vitro pre-sexual stages"),
      ("42020723", "", "single-cell atlas of sexual development, 2026")]),
    ("transcription · per cell-cycle phase", "transcription", "cell cycle", "gene", [], "one",
     [("32065584", "", "the study behind cellcycle_phase, re-ingested as VALUES not a call")]),
    ("transcription · in naive macrophage", "transcription", "host: naive macrophage", "gene", [],
     "one", [("40630957", "GSE295224", "dual single-cell and bulk, host-parasite")]),
    ("transcription · in IFN-gamma macrophage", "transcription", "host: IFN-g macrophage", "gene",
     [], "one", []),
    ("transcription · in vivo brain", "transcription", "host: brain", "gene", [], "one",
     [("41278634", "", "single-cell brain-derived bradyzoites, 2025")]),
    ("transcription · under stress / conversion", "transcription", "alkaline, stress", "gene",
     ["stress_"], "separate", []),
    ("transcription · under TF or chromatin perturbation", "transcription", "perturbation", "gene",
     ["morc_"], "separate",
     [("39774584", "PRJNA1134678", "ApiAP2 cascade"), ("40920096", "PRJNA1281009", "AP2X-7"),
      ("41193469", "GSE287537", "SWI/SNF"), ("40879678", "GSE286088", "GCN5a"),
      ("40593611", "GSE268652", "SNF2L")]),

    # ---------------------------------------------------------------- translation
    ("translation · tachyzoite", "translation", "tachyzoite, in vitro", "gene", [], "one",
     [("29228904", "GSE99395", "comparative ribosome profiling"),
      ("38782906", "GSE245775", "eIF1.2 and stage conversion")]),
    ("translation · bradyzoite", "translation", "bradyzoite", "gene", [], "one",
     [("29228904", "GSE99395", "same study covers the conversion")]),
    ("translation · per cell-cycle phase", "translation", "cell cycle", "gene", [], "one", []),
    ("translation · under stress", "translation", "stress, iron", "gene", [], "one",
     [("41925342", "", "translational remodelling under iron starvation, 2026")]),

    # ---------------------------------------------------------------- protein level
    ("protein abundance · tachyzoite", "protein abundance", "tachyzoite", "gene",
     ["proteome_", "protein_ibaq_log2"], "fill",
     [("40716488", "PXD063409", "cytoskeleton proteome"),
      ("25867681", "PXD000297", "proteogenomics")]),
    ("protein abundance · other life stages", "protein abundance", "stages", "gene", ["oocyst_"],
     "separate", [("28626452", "PXD003765", "iTRAQ across developmental stages")]),
    ("protein turnover / stability", "protein abundance", "tachyzoite", "gene", [], "one",
     [("35976251", "PXD033642", "temporal and thermal proteome profiling")]),

    # ---------------------------------------------------------------- modifications
    ("phosphorylation · site count", "PTM", "tachyzoite", "gene", ["n_phosphosites", "has_phospho"],
     "one", []),
    ("phosphorylation · quantitative", "PTM", "tachyzoite", "gene", ["phospho_"], "average",
     [("33363051", "PXD020655", "iTRAQ phosphoproteome"),
      ("31508380", "PXD007777", "type I vs type II"),
      ("40901993", "PXD064226", "PP2A-2 during cytokinesis")]),
    ("phosphorylation · kinase-substrate", "PTM", "perturbation", "gene", [], "separate",
     [("37933960", "PXD019677", "CDPK1 substrates"), ("33635921", "PXD019655", "CDPK7")]),
    ("acetylation", "PTM", "life stages", "gene", [], "one",
     [("37562054", "PXD040368", "lysine acetylation across stages")]),
    ("lactylation", "PTM", "tachyzoite", "gene", [], "one",
     [("36216028", "PXD022700", "protein lactylation")]),
    ("S-nitrosylation", "PTM", "tachyzoite", "gene", [], "one",
     [("37959749", "PXD046083", "proteome-wide cysteine S-nitrosylation")]),
    ("ubiquitination / SUMOylation", "PTM", "tachyzoite", "gene", [], "one",
     [("40348811", "PXD045018", "TgUAE1"), ("40590555", "PXD054719", "endodyogeny")]),
    ("glycosylation", "PTM", "tachyzoite", "gene", [], "one",
     [("39912628", "PXD056853", "nucleocytoplasmic O-fucose")]),
    ("palmitoylation", "PTM", "tachyzoite", "gene", [], "one", []),

    # ---------------------------------------------------------------- fitness
    ("fitness · HFF in vitro", "fitness", "HFF", "gene", ["fit_invitro_hff"], "one", []),
    ("fitness · naive macrophage", "fitness", "naive BMDM", "gene", ["fit_naive_bmdm"], "one", []),
    ("fitness · IFN-gamma macrophage", "fitness", "IFN-g BMDM", "gene", ["fit_ifng"], "one",
     [("36916910", "", "a second IFN-gamma screen")]),
    ("fitness · in vivo peritoneum", "fitness", "mouse peritoneum", "gene", ["fit_invivo_PE"],
     "one", []),
    ("fitness · in vivo lung", "fitness", "mouse lung", "gene", ["fit_invivo_lung"], "one", []),
    ("fitness · in vivo liver", "fitness", "mouse liver", "gene", ["fit_invivo_liver"], "one", []),
    ("fitness · in vivo spleen", "fitness", "mouse spleen", "gene", ["fit_invivo_spleen"], "one",
     []),
    ("fitness · in vivo brain, acute", "fitness", "mouse brain, acute", "gene",
     ["invivo_WholeBrain_Acute"], "average", []),
    ("fitness · in vivo brain, chronic", "fitness", "mouse brain, chronic", "gene",
     ["invivo_WholeBrain_Chronic", "invivo_BZ_"], "average", []),
    ("fitness · oxidative stress", "fitness", "oxidant", "gene", [], "one",
     [("34163449", "PRJNA707360", "genome-wide oxidative-stress screen")]),
    ("fitness · hyperLOPIT-unassigned proteins", "fitness", "in vivo virulence", "gene", [], "one",
     [("39082802", "GSE253884", "aimed at this map's largest gap")]),
    ("genetic interaction · delta-GRA17", "fitness", "GRA17 background", "gene",
     ["crispr_gra17"], "one", []),
    ("stage-conversion phenotype", "fitness", "bradyzoite conversion", "gene", [], "one", []),
    ("drug sensitivity", "fitness", "compound", "gene", [], "separate", []),

    # ---------------------------------------------------------------- regulation
    ("TF binding · per factor", "regulation", "ChIP / CUT&RUN", "gene", [], "separate",
     [("29788176", "GSE106864", "ApiAP2 cooperative binding"),
      ("37350586", "GSE228853", "BDP1 bromodomain")]),
    ("chromatin state · histone marks", "regulation", "tachyzoite / bradyzoite", "gene", [], "fill",
     [("35164683", "GSE104347", "histone variants genome-wide"),
      ("21179246", "GSE22100", "GCN5-A under alkaline stress")]),
    ("chromatin accessibility", "regulation", "stages", "gene", [], "one",
     [("38093015", "PRJNA921935", "pre-sexual stages")]),
    ("RNA modification · m6A / 5mC", "regulation", "tachyzoite", "gene", [], "separate",
     [("34263725", "GSE168155", "m6A reader and polyadenylation"),
      ("40830525", "GSE294543", "5mC methylome across lineages")]),
    ("splicing / isoform use", "regulation", "stages", "gene", [], "one",
     [("33688018", "PRJNA606986", "nanopore isoform landscape")]),
    ("RNA stability / half-life", "regulation", "tachyzoite", "gene", [], "one",
     [("39899594", "PRJEB67890", "iron-mediated post-transcriptional regulation")]),

    # ---------------------------------------------------------------- localisation and exposure
    ("localization · measured", "localization", "hyperLOPIT", "gene",
     ["compartment", "lopit_prob", "lopit_methods_agree"], "one", []),
    ("localization · transferred", "localization", "orthoLOPIT", "gene",
     ["ortholopit_", "compartment_best"], "fill", []),
    ("membrane topology", "localization", "sequence", "gene",
     ["dtm_class", "n_tm", "has_signal_peptide", "is_tm", "tm_kd_"], "one", []),
    ("exposure to host cytosol", "localization", "PVM, export", "gene", [], "fill",
     [("38747635", "", "TurboID exportome of secreted disordered proteins"),
      ("29615509", "GSE109830", "MYR1-dependent effectors"),
      ("31366709", "GSE122786", "translocation across the PVM")]),
    ("secretome / excreted", "localization", "ESA", "gene", [], "one",
     [("41137792", "PXD028969", "secretome and transcriptome")]),

    # ---------------------------------------------------------------- relations (gene pairs)
    ("co-transcription", "relation", "stage series", "pair", ["edge:coexpression"], "separate", []),
    ("co-translation", "relation", "ribosome profiling", "pair", [], "separate", []),
    ("co-fitness", "relation", "seven screens", "pair", ["edge:cofitness"], "separate", []),
    ("interaction · crosslink MS", "relation", "measured contact", "pair", ["edge:xlms"], "one",
     []),
    ("interaction · IP-MS, parasite-parasite", "relation", "pulldown", "pair", ["edge:ip_ms"],
     "fill", [("", "", "55 IP-MS studies already downloaded and not curated")]),
    ("interaction · proximity labelling", "relation", "BioID / TurboID", "pair", [], "fill",
     [("", "", "44 BioID studies already downloaded"),
      ("36214684", "PXD032102", "calmodulin proximal interactors")]),
    ("interaction · structural similarity", "relation", "Foldseek", "pair", ["edge:struct"], "one",
     []),
    ("interaction · with host proteins", "relation", "host IP-MS", "pair", [], "separate",
     [("32075880", "PXD016383", "MYR1 co-IP"), ("38747635", "", "exportome TurboID")]),
    ("shared compartment", "relation", "hyperLOPIT", "pair", ["edge:compartment"], "one", []),
    ("shared orthogroup", "relation", "OrthoMCL", "pair", ["edge:orthogroup"], "one", []),
    ("shared domain", "relation", "InterPro", "pair", ["edge:domain"], "one", []),

    # ---------------------------------------------------------------- host effect
    ("host transcriptional effect per effector", "host effect", "dual perturb-seq", "gene",
     ["hosttx_"], "one",
     [("37827122", "GSE229505", "the per-effector host signature, not just its p-value")]),

    # ---------------------------------------------------------------- sequence and conservation
    ("domain content", "sequence", "InterPro", "gene", ["n_interpro", "has_domain"], "one", []),
    ("fold confidence / disorder", "sequence", "AlphaFold", "gene", ["mean_plddt", "has_structure"],
     "one", []),
    ("conservation breadth", "sequence", "OrthoMCL", "gene",
     ["has_pf_ortholog", "has_cp_ortholog", "lineage_specific"], "one", []),
    ("paralogy", "sequence", "OrthoMCL", "gene", ["paralog_number"], "one", []),
    ("sequence basics", "sequence", "protein", "gene", ["length"], "one", []),
    ("strain variation", "sequence", "population", "gene", [], "one", []),

    # ---------------------------------------------------------------- not a feature
    ("literature attention", "NEVER a feature", "PubMed / PMC", "gene",
     ["n_publications", "n_fulltext", "n_papers_", "attention_depth", "lit_tier"], "one", []),
]


def coverage(nodes, patterns):
    """How many genes carry a value in the columns this slot is filled by."""
    cols = [c for c in nodes.columns if any(c == p or c.startswith(p) for p in patterns)]
    if not cols:
        return 0, []
    return int(nodes[cols].notna().any(axis=1).sum()), cols


def grade(frac: float, filled: bool, unit: str) -> str:
    """A for genome-wide and measured, B for partial, C for thin or indirect, - for empty."""
    if not filled:
        return "-"
    if unit == "pair":
        return "A" if frac >= 0.25 else ("B" if frac >= 0.05 else "C")
    return "A" if frac >= 0.8 else ("B" if frac >= 0.2 else "C")


def _write_markdown(rows) -> None:
    """The same table, rendered. One file to read, one file to compute with."""
    by_axis = {}
    for r in rows:
        by_axis.setdefault(r["axis"], []).append(r)
    lines = [PROSE]
    counts = {g: sum(1 for r in rows if r["grade"] == g) for g in ("A", "B", "C", "-")}
    lines.append(f"**{len(rows)} slots: {counts['A']} covered well, {counts['B']} partly, "
                 f"{counts['C']} thinly, {counts['-']} empty.**\n")
    for axis, group in by_axis.items():
        lines.append(f"### {axis}\n")
        lines.append("| slot | context | grade | genes | coverage | filled by | policy | "
                     "candidates to fill or improve it |")
        lines.append("|---|---|---|---|---|---|---|---|")
        for r in group:
            cands = r["candidates"] or ""
            for token in cands.split("PMID ")[1:]:
                pmid = token.split()[0]
                cands = cands.replace(f"PMID {pmid}",
                                      f"[{pmid}](https://pubmed.ncbi.nlm.nih.gov/{pmid}/)")
            lines.append(f"| {r['slot']} | {r['context']} | **{r['grade']}** | "
                         f"{r['genes'] or ''} | {r['coverage']} | `{r['filled_by']}` | "
                         f"{r['policy']} | {cands} |")
        lines.append("")

    # One dataset, several slots -- the many-to-many, read off the table itself.
    shared = {}
    for r in rows:
        for token in (r["candidates"] or "").split(";"):
            token = token.strip()
            if token.startswith("PMID "):
                pmid = token.split()[1]
                shared.setdefault(pmid, []).append(r["slot"])
    multi = {p: s for p, s in shared.items() if len(s) > 1}
    for r in rows:
        for col in r["filled_by"].split(", "):
            if col and not col.startswith("edge:"):
                shared.setdefault(col, []).append(r["slot"])
    multi_cols = {c: s for c, s in shared.items()
                  if len(s) > 1 and not c.isdigit()}
    if multi or multi_cols:
        lines.append("### One dataset, several slots\n")
        lines.append("Read off the table above: this is the many-to-many the mechanism has to "
                     "carry, not a special case.\n")
        lines.append("| dataset or column family | slots it fills |")
        lines.append("|---|---|")
        for key, slots in list(multi.items()) + list(multi_cols.items()):
            name = (f"[PMID {key}](https://pubmed.ncbi.nlm.nih.gov/{key}/)" if key.isdigit()
                    else f"`{key}`")
            lines.append(f"| {name} | {'; '.join(sorted(set(slots)))} |")
        lines.append("")
    open(OUT_MD, "w", encoding="utf8").write("\n".join(lines))


def main() -> int:
    import numpy as np
    import pandas as pd
    from starplast import paths

    nodes = pd.read_parquet(paths.cache_file("nodes.parquet"))
    z = np.load(paths.cache_file("graph.npz"), allow_pickle=True)
    n_genes = len(nodes)

    rows = []
    for slot, axis, context, unit, fills, policy, cands in SLOTS:
        edges = [f[len("edge:"):] for f in fills if f.startswith("edge:")]
        columns = [f for f in fills if not f.startswith("edge:")]
        if edges:
            key = f"{edges[0]}__a"
            pairs = int(len(z[key])) if key in z.files else 0
            covered = int(len(set(np.concatenate([z[f"{edges[0]}__a"], z[f"{edges[0]}__b"]]))
                              )) if key in z.files else 0
            detail = f"{pairs:,} pairs"
        else:
            covered, cols = coverage(nodes, columns)
            pairs = 0
            detail = f"{len(cols)} columns" if cols else ""
        frac = covered / n_genes if n_genes else 0.0
        rows.append({
            "slot": slot, "axis": axis, "context": context, "unit": unit,
            "grade": grade(frac, bool(covered), unit),
            "genes": covered, "coverage": f"{frac:.1%}" if covered else "",
            "filled_by": ", ".join(edges or columns), "detail": detail, "policy": policy,
            "candidates": "; ".join(f"PMID {p} {a}".strip() + (f" ({n})" if n else "")
                                    for p, a, n in cands),
        })

    os.makedirs(os.path.dirname(OUT_CSV), exist_ok=True)
    with open(OUT_CSV, "w", newline="", encoding="utf8") as fh:
        w = csv.DictWriter(fh, fieldnames=list(rows[0]))
        w.writeheader()
        w.writerows(rows)
    _write_markdown(rows)
    empty = sum(1 for r in rows if r["grade"] == "-")
    print(f"{len(rows)} slots -> {OUT_CSV} and {OUT_MD}")
    print(f"  A {sum(1 for r in rows if r['grade'] == 'A')}   "
          f"B {sum(1 for r in rows if r['grade'] == 'B')}   "
          f"C {sum(1 for r in rows if r['grade'] == 'C')}   empty {empty}")
    return len(rows)


if __name__ == "__main__":
    main()
