#!/usr/bin/env python3
"""Audit the slot grouping for information leakage, and write down what the data says.

Runs `starplast.leakage` over both shipped tables and writes ``results/leakage_audit_<date>/``:

    calibration.json     per organism: how associated columns from DIFFERENT axes of the catalogue
                         get (95th, 99th, 99.9th percentiles, bootstrap 95% intervals over slot
                         pairs), on ranks and on the closure's combined measure
    relations.csv        the association distribution per declared relation (same slot, same
                         experiment, same quantity, same family, same axis, different axis)
    gaps.csv             column pairs associated at or above the closure's threshold that the
                         closure does NOT remove -- should be empty
    residual_leaks.csv   per held-out target, every slot the closure permits and how well it alone
                         predicts the target; flagged rows are candidate undeclared derivations
    report.md            the numbers above, in sentences

Run:  python scripts/leakage_audit.py
"""
from __future__ import annotations

import datetime as _dt
import json
import os
import sys

import pandas as pd

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

from starplast import leakage as L  # noqa: E402

TABLES = {"Tg": "nodes.parquet", "Pf": "pf_nodes.parquet"}
TARGETS = {"Tg": ("compartment", "lopit_unified", "cellcycle_phase", "stage_enriched_derived",
                  "dtm_class", "screen_any_phenotype", "fit_invitro_hff",
                  "fit_serum_differential_p8", "fit_invivo_heart",
                  "mrna_log2_remaining_4h_actinomycin", "fit_glucose_dependence",
                  "iron_depletion_protein_log2fc", "utr5_n_uaugs", "bzsub_A_expr"),
           "Pf": ("pb_transferred_phenotype", "stage_enriched_derived", "is_exported",
                  "piggybac_mis", "melting_temperature_tm", "fertility_female")}
THRESHOLD = 0.8


def audit(out_dir: str, log=print) -> dict:
    """Run every part of the audit and write the files. Returns the calibration."""
    import numpy as np
    os.makedirs(out_dir, exist_ok=True)
    cal, relations, gaps, residual = {}, [], [], []
    for org, name in TABLES.items():
        nodes = pd.read_parquet(os.path.join(ROOT, "starplast", "data", name))
        log(f"{org}: association matrix")
        ranks, values = L.association_matrix(nodes)
        owner = L.slot_of_columns(nodes, org)
        pairs = L.pair_table(ranks, values, owner, org)
        on_ranks = pairs.assign(association=pairs["rank_association"])
        cal[org] = {"columns": int(len(ranks)), "pairs": int(len(pairs)),
                    "ranks": {str(q): L.calibrate(on_ranks, q, n_boot=500)
                              for q in (0.95, 0.99, 0.999)},
                    "combined": {str(q): L.calibrate(pairs, q, n_boot=500)
                                 for q in (0.95, 0.99, 0.999)},
                    "closure_threshold": THRESHOLD,
                    "closure_threshold_percentile_on_ranks": float(
                        (on_ranks.loc[on_ranks.relation == "different axis", "association"]
                         .dropna() < THRESHOLD).mean() * 100)}
        for rel, g in pairs.groupby("relation"):
            v = g["rank_association"].dropna()
            relations.append({"organism": org, "relation": rel, "pairs": len(v),
                              "median": float(v.median()), "p90": float(v.quantile(0.9)),
                              "p99": float(v.quantile(0.99)), "max": float(v.max()),
                              "share_at_or_above_threshold": float((v >= THRESHOLD).mean())})
        log(f"{org}: closure gaps")
        g = L.closure_gaps(nodes, on_ranks, THRESHOLD)
        gaps.append(g.assign(organism=org))
        for t in TARGETS[org]:
            if t in nodes.columns:
                log(f"{org}: residual leaks for {t}")
                residual.append(L.residual_leaks(nodes, t, organism=org).assign(organism=org))
    with open(os.path.join(out_dir, "calibration.json"), "w") as fh:
        json.dump(cal, fh, indent=1)
    pd.DataFrame(relations).to_csv(os.path.join(out_dir, "relations.csv"), index=False)
    gaps_df = pd.concat(gaps, ignore_index=True)
    gaps_df.to_csv(os.path.join(out_dir, "gaps.csv"), index=False)
    res = pd.concat(residual, ignore_index=True)
    res.to_csv(os.path.join(out_dir, "residual_leaks.csv"), index=False)
    lines = [f"# Leakage audit, {os.path.basename(out_dir).split('_')[-1]}", "",
             "Generated by `scripts/leakage_audit.py`.", ""]
    for org in TABLES:
        c = cal[org]
        r99, r999 = c["ranks"]["0.99"], c["ranks"]["0.999"]
        lines += [f"## {org}", "",
                  f"{c['columns']} measured columns, {c['pairs']:,} pairs. Between columns from "
                  f"different axes of the catalogue, rank association reaches "
                  f"{r99['threshold']:.3f} at the 99th percentile (95% CI {r99['low']:.3f}-"
                  f"{r99['high']:.3f}) and {r999['threshold']:.3f} at the 99.9th "
                  f"({r999['low']:.3f}-{r999['high']:.3f}). The closure's threshold, "
                  f"{THRESHOLD}, sits at the {c['closure_threshold_percentile_on_ranks']:.1f}th "
                  f"percentile of that distribution.", ""]
        n_gaps = int((gaps_df["organism"] == org).sum()) if len(gaps_df) else 0
        flagged = res[(res["organism"] == org) & res["flag"]]
        lines += [f"Closure gaps at {THRESHOLD}: **{n_gaps}**. Residual leaks flagged: "
                  f"**{len(flagged)}**" + (": " + ", ".join(
                      f"{r.target} <- {r.slot} ({r.predictability:.2f})"
                      for r in flagged.itertuples()) if len(flagged) else "") + ".", ""]
        top = (res[res["organism"] == org].sort_values("predictability", ascending=False)
               .groupby("target").head(1))
        lines += ["Strongest permitted predictor of each held-out target:", "",
                  "| target | slot | predictability | robust z |", "|---|---|---|---|"]
        lines += [f"| {r.target} | {r.slot} | {r.predictability:.3f} | {r.robust_z:.1f} |"
                  for r in top.itertuples()] + [""]
    with open(os.path.join(out_dir, "report.md"), "w") as fh:
        fh.write("\n".join(lines))
    log(f"wrote {out_dir}")
    return cal


def main(argv=None, log=print) -> int:
    """Audit into results/leakage_audit_<today>/."""
    out = os.path.join(ROOT, "results", f"leakage_audit_{_dt.date.today().isoformat()}")
    audit(out, log=log)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
