#!/usr/bin/env python3
"""Measure every strategy on the shipped tables, and write down what each one earned.

Runs each strategy's self-test on each organism's packaged table at its default settings and
writes three things:

* ``starplast/data/strategy_selftests.json`` -- the verdicts the Strategies tab shows beside each
  strategy, so how far to trust one is visible before anything is run;
* ``results/strategies_<date>/selftests_<organism>.csv`` -- the same numbers as a table, with the
  hidden-set size, the null and the time taken;
* ``docs/strategies.md`` -- the catalogue: every strategy's question, explanation, walkthrough,
  how it is tested, and what it measured here.

A FAIL is written down as a FAIL. The point of the file is that a strategy's trustworthiness on
THIS data is a measured number, and a catalogue that quietly left out the strategies that did not
work would be the survivorship this project exists to avoid.

Run:  python scripts/strategy_selftests.py            # both organisms, every strategy
      python scripts/strategy_selftests.py --organism Tg --only feature_knn,layer_vote
      python scripts/strategy_selftests.py --docs-only  # regenerate the document from the JSON
"""
from __future__ import annotations

import argparse
import datetime as _dt
import json
import os
import sys
import time

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from starplast import strategies as S  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
JSON_OUT = os.path.join(ROOT, "starplast", "data", "strategy_selftests.json")
DOC_OUT = os.path.join(ROOT, "docs", "strategies.md")
ORGANISMS = {"Tg": "Toxoplasma gondii", "Pf": "Plasmodium falciparum"}


def measure(organism: str, only=None, log=print) -> dict:
    """Every strategy's self-test on one organism's shipped table: key -> result dict."""
    ctx = S.Context.shipped(organism)
    out = {}
    for s in S.catalog():
        if only and s.key not in only:
            continue
        t0 = time.monotonic()
        try:
            r = s.test(ctx)
            out[s.key] = r.to_dict()
            log(f"{organism} {s.number:02d} {s.key:24s} {time.monotonic() - t0:6.1f}s  {r.summary()}")
        except Exception as exc:                # recorded, because a strategy that cannot run on
            out[s.key] = {"strategy": s.key,    # this table is itself a measured fact about it
                          "verdict": "NOT RUN", "note": f"{type(exc).__name__}: {exc}",
                          "seconds": round(time.monotonic() - t0, 1)}
            log(f"{organism} {s.number:02d} {s.key:24s} could not run: {type(exc).__name__}: {exc}")
    return out


def write_tables(results: dict, stamp: str) -> list:
    """One CSV per organism under results/, for reading the numbers without the application."""
    import pandas as pd
    folder = os.path.join(ROOT, "results", f"strategies_{stamp}")
    os.makedirs(folder, exist_ok=True)
    paths = []
    for org, by_key in results.items():
        if org.startswith("_"):
            continue
        rows = []
        for s in S.catalog():
            r = by_key.get(s.key)
            if r is None:
                continue
            rows.append({"number": s.number, "key": s.key, "title": s.title, "family": s.family,
                         **{k: v for k, v in r.items() if k not in ("strategy", "numbers")}})
        path = os.path.join(folder, f"selftests_{org}.csv")
        pd.DataFrame(rows).to_csv(path, index=False)
        paths.append(path)
    return paths


def _cell(r: dict) -> str:
    if not r:
        return "not measured"
    if r.get("verdict") in ("INCONCLUSIVE", "NOT RUN"):
        return f"{r['verdict']} ({r.get('note', '')})"
    return (f"**{r['verdict']}** -- {r['metric']} {r['observed']:.3f} against "
            f"{r['null_mean']:.3f} under {r['null_kind']}; {r['n_hidden']:,} hidden")


def write_doc(results: dict) -> str:
    """The catalogue as a document, with each strategy's measured verdict in place."""
    lines = ["# Strategies", "",
             "Generated by `scripts/strategy_selftests.py` from `starplast/strategy_catalog.py` and "
             "the measured verdicts in `starplast/data/strategy_selftests.json` -- edit those, not "
             "this file.", "",
             "A strategy is a named way of using the combined data to infer something nobody has "
             "measured. Each one below comes with the question it answers, why its inference works "
             "and how it fails, a walkthrough, and a **self-test**: known information is hidden, the "
             "strategy is asked for it back, and its answer is compared with the same procedure run "
             "on shuffled labels, random gene sets or permuted identities. It passes only when it "
             "beats that null's 95th percentile by the stated margin. The verdicts are what each "
             "strategy earned on the shipped tables at its default settings; a FAIL is reported as a "
             "FAIL.", "",
             f"Measured {results.get('_measured', 'not yet')}.", "",
             "| # | strategy | family | " + " | ".join(ORGANISMS[o] for o in ORGANISMS
                                                     if o in results) + " |",
             "|---|---|---|" + "---|" * sum(o in results for o in ORGANISMS)]
    for s in S.catalog():
        cells = [(results.get(o, {}).get(s.key) or {}).get("verdict", "--")
                 for o in ORGANISMS if o in results]
        lines.append(f"| {s.number:02d} | [{s.title}](#{s.number:02d}-{s.key}) | {s.family} | "
                     + " | ".join(cells) + " |")
    lines.append("")
    for fam in S.families():
        lines += [f"## {fam}", ""]
        for s in [x for x in S.catalog() if x.family == fam]:
            lines += [f"### {s.number:02d} {s.key}", "", f"**{s.title}.** *{s.question}*", ""]
            lines += [p for para in s.explanation.split("\n\n") for p in (para, "")]
            lines += ["**Walkthrough**", ""]
            lines += [f"{i}. {step}" for i, step in enumerate(s.walkthrough, 1)] + [""]
            lines += ["**How it is tested.** " + s.test_description, ""]
            for org in ORGANISMS:
                if org in results:
                    lines += [f"*On {ORGANISMS[org]}:* {_cell(results[org].get(s.key))}", ""]
            lines += ["**Settings:** " + "; ".join(f"`{p.name}` -- {p.tip}" for p in s.params), ""]
    with open(DOC_OUT, "w") as fh:
        fh.write("\n".join(lines))
    return DOC_OUT


def main(argv=None, log=print) -> int:
    """Measure, then write the JSON, the tables and the document."""
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--organism", choices=sorted(ORGANISMS), action="append")
    ap.add_argument("--only", default="", help="comma-separated strategy keys")
    ap.add_argument("--docs-only", action="store_true",
                    help="regenerate docs/strategies.md from the JSON without measuring")
    args = ap.parse_args(argv)
    existing = {}
    if os.path.exists(JSON_OUT):
        with open(JSON_OUT) as fh:
            existing = json.load(fh)
    if args.docs_only:
        log(f"wrote {write_doc(existing)}")
        return 0
    only = {k for k in args.only.split(",") if k} or None
    stamp = _dt.date.today().isoformat()
    for org in args.organism or sorted(ORGANISMS, reverse=True):
        measured = measure(org, only, log=log)
        existing.setdefault(org, {}).update(measured)
    existing["_measured"] = stamp
    with open(JSON_OUT, "w") as fh:
        json.dump(existing, fh, indent=1, sort_keys=True)
    log(f"wrote {JSON_OUT}")
    for path in write_tables(existing, stamp):
        log(f"wrote {path}")
    log(f"wrote {write_doc(existing)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
